// renderer implementation — display + LVGL bring-up via the Waveshare BSP,
// and the LittleFS -> PSRAM sprite loader (build-order step 5, phase ②).
// Gene-palette tinting (③) and layered composition (④) are still stubbed:
// renderer_draw_pet() remains the step-3 placeholder circle until ④.

#include "renderer.h"

#include <dirent.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#include "esp_heap_caps.h"
#include "esp_littlefs.h"
#include "esp_log.h"
#include "esp_random.h"            // wander picks random targets / durations
#include "bsp/esp-bsp.h"
#include "renderer_emotes.h"   // generated by sprite_forge/emotes_to_c.py

static const char *TAG = "renderer";
static lv_display_t *s_disp;
static bool s_fs_ok;
static pet_sprites_t s_sprites;
static palette_t s_pal_body;   // loaded once at boot; lives for process life
static palette_t s_pal_eye;

#define ASSETS_BASE   "/assets"
#define ASSETS_LABEL  "assets"
#define ANCHOR_MAGIC  "PANC"
#define PALETTE_MAGIC "PPAL"
#define MAX_SHAPES    16     // shapes per (stage,layer); gene clamps into this
// Big enough for GCC's worst-case format-truncation analysis: a parent dir
// path plus a NAME_MAX (255) filename plus ".bin" can theoretically be 512+.
// In practice every path we build is short ("/assets/baby/body/round/idle.bin"
// ≈ 35 chars); buffer is over-sized so -Werror=format-truncation accepts it.
#define PATH_MAX_LEN  512

// pet_stage_t -> directory name (mirrors forge_common.STAGES / architecture).
static const char *const STAGE_DIR[] = {
    "egg", "baby", "child", "teen", "adult", "elder",
};

// sprite_layer_t -> directory name (mirrors forge_common.LAYERS).
static const char *const LAYER_DIR[LAYER_COUNT] = {
    [LAYER_BODY] = "body",   [LAYER_TAIL]    = "tail",
    [LAYER_EARS] = "ears",   [LAYER_MOUTH]   = "mouth",
    [LAYER_EYES] = "eyes",   [LAYER_PATTERN] = "pattern",
    [LAYER_ACCESSORY] = "accessory",
};

// Resting animation per layer for step 5 (architecture §5.5). If the file
// is absent the loader falls back to the first *.bin in the shape dir.
static const char *const LAYER_ANIM[LAYER_COUNT] = {
    [LAYER_BODY] = "idle",   [LAYER_TAIL]    = "idle",
    [LAYER_EARS] = "idle",   [LAYER_MOUTH]   = "neutral",
    [LAYER_EYES] = "normal", [LAYER_PATTERN] = "idle",
    [LAYER_ACCESSORY] = "idle",
};

// Which gene picks each layer's shape. Tail follows the body shape (no tail
// gene exists in gene_spec); accessory has no gene yet -> index 0.
// ASSUMPTION (confirm): tail==body_shape, accessory==slot 0.
static uint8_t layer_gene_value(const Pet *pet, sprite_layer_t layer)
{
    switch (layer) {
    case LAYER_BODY:
    case LAYER_TAIL:      return pet->genes[GENE_BODY_SHAPE];
    case LAYER_EARS:      return pet->genes[GENE_EAR_SHAPE];
    case LAYER_MOUTH:     return pet->genes[GENE_MOUTH_SHAPE];
    case LAYER_EYES:      return pet->genes[GENE_EYE_SHAPE];
    case LAYER_PATTERN:   return pet->genes[GENE_PATTERN];
    case LAYER_ACCESSORY: return 0;
    default:              return 0;
    }
}

static uint8_t format_bpp(uint8_t fmt)
{
    switch (fmt) {
    case SPRITE_FMT_GRAY_ALPHA: return 2;
    case SPRITE_FMT_PALETTIZED: return 1;
    case SPRITE_FMT_RGB565:     return 2;
    default:                    return 0;
    }
}

static int cmp_str(const void *a, const void *b)
{
    return strcmp((const char *)a, (const char *)b);
}

// Resolve a gene value to a shape directory name within {base}.
// Shapes are the sorted subdirectory list; gene is taken modulo the count
// (gene_spec.md: out-of-range clamps to table size, never rejects).
// Returns false if the layer has no shapes (caller skips the layer).
static bool resolve_shape(const char *base, uint8_t gene,
                          char out[NAME_MAX + 1])
{
    DIR *d = opendir(base);
    if (!d) {
        return false;
    }
    static char names[MAX_SHAPES][NAME_MAX + 1];
    int n = 0;
    struct dirent *e;
    while ((e = readdir(d)) != NULL && n < MAX_SHAPES) {
        if (e->d_name[0] == '.') {
            continue;
        }
        char p[PATH_MAX_LEN];
        struct stat st;
        snprintf(p, sizeof(p), "%s/%s", base, e->d_name);
        if (stat(p, &st) == 0 && S_ISDIR(st.st_mode)) {
            strncpy(names[n], e->d_name, NAME_MAX);
            names[n][NAME_MAX] = '\0';
            n++;
        }
    }
    closedir(d);
    if (n == 0) {
        return false;
    }
    qsort(names, n, sizeof(names[0]), cmp_str);
    strcpy(out, names[gene % n]);
    return true;
}

// Pick {shape_dir}/{anim}.bin, else the alphabetically-first *.bin in
// {shape_dir}. The fallback MUST sort: LittleFS readdir order is hash/
// insertion order, so taking the raw-first entry would load a
// boot-dependent, non-deterministic frame once a shape has >1 animation.
static bool resolve_sprite_file(const char *shape_dir, const char *anim,
                                char out[PATH_MAX_LEN])
{
    struct stat st;
    snprintf(out, PATH_MAX_LEN, "%s/%s.bin", shape_dir, anim);
    if (stat(out, &st) == 0) {
        return true;
    }
    DIR *d = opendir(shape_dir);
    if (!d) {
        return false;
    }
    static char bins[MAX_SHAPES][NAME_MAX + 1];
    int nb = 0;
    struct dirent *e;
    while ((e = readdir(d)) != NULL && nb < MAX_SHAPES) {
        const char *dot = strrchr(e->d_name, '.');
        if (dot && strcmp(dot, ".bin") == 0
            && strcmp(e->d_name, "anchors.bin") != 0) {
            strncpy(bins[nb], e->d_name, NAME_MAX);
            bins[nb][NAME_MAX] = '\0';
            nb++;
        }
    }
    closedir(d);
    if (nb == 0) {
        return false;
    }
    qsort(bins, nb, sizeof(bins[0]), cmp_str);
    snprintf(out, PATH_MAX_LEN, "%s/%s", shape_dir, bins[0]);
    return true;
}

// Read a PSPR sheet into a freshly PSRAM-allocated buffer.
static bool load_sprite(const char *path, sprite_t *out)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        return false;
    }
    sprite_header_t hdr;
    bool ok = false;
    uint8_t *buf = NULL;
    if (fread(&hdr, 1, sizeof(hdr), f) != sizeof(hdr)) {
        goto done;
    }
    if (memcmp(hdr.magic, SPRITE_MAGIC, 4) != 0) {
        ESP_LOGW(TAG, "%s: bad magic", path);
        goto done;
    }
    uint8_t bpp = format_bpp(hdr.format);
    if (bpp == 0 || hdr.width == 0 || hdr.height == 0
        || hdr.num_frames == 0) {
        ESP_LOGW(TAG, "%s: bad header", path);
        goto done;
    }
    size_t sz = (size_t)hdr.width * hdr.height * hdr.num_frames * bpp;
    buf = heap_caps_malloc(sz, MALLOC_CAP_SPIRAM);
    if (!buf) {
        ESP_LOGE(TAG, "%s: PSRAM alloc %u failed", path, (unsigned)sz);
        goto done;
    }
    if (fread(buf, 1, sz, f) != sz) {
        ESP_LOGW(TAG, "%s: short read", path);
        heap_caps_free(buf);
        buf = NULL;
        goto done;
    }
    out->hdr = hdr;
    out->pixels = buf;
    ok = true;
done:
    fclose(f);
    return ok;
}

// Decode anchors.bin ("PANC", u8 ver, u8 count, count*(i16 x,i16 y)).
//
// Supports v1 (count=5: eyes/mouth/ears/tail/accessory) and v2 (count=6:
// adds `pattern` at the end). v1 files load with pattern defaulting to
// (0, 0) — that's fine because the renderer masks pattern writes to body
// alpha so positioning is forgiving (see compose_pet).
static bool load_anchors(const char *path, sprite_anchors_t *out)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        return false;
    }
    uint8_t hdr[6];
    bool ok = false;
    if (fread(hdr, 1, sizeof(hdr), f) != sizeof(hdr)) {
        goto done;
    }
    uint8_t ver = hdr[4];
    uint8_t cnt = hdr[5];
    bool v1 = (memcmp(hdr, ANCHOR_MAGIC, 4) == 0 && ver == 1 && cnt == 5);
    bool v2 = (memcmp(hdr, ANCHOR_MAGIC, 4) == 0 && ver == 2 && cnt == 6);
    if (!v1 && !v2) {
        ESP_LOGW(TAG, "%s: bad anchors header (ver=%u cnt=%u)",
                 path, ver, cnt);
        goto done;
    }
    int16_t pts[12];   // v2 uses 12 ints; v1 reads first 10.
    size_t expect = (size_t)cnt * 4;   // bytes
    if (fread(pts, 1, expect, f) != expect) {
        goto done;
    }
    // Order: eyes, mouth, ears, tail, accessory[, pattern].
    memcpy(out->eyes,      &pts[0], 4);
    memcpy(out->mouth,     &pts[2], 4);
    memcpy(out->ears,      &pts[4], 4);
    memcpy(out->tail,      &pts[6], 4);
    memcpy(out->accessory, &pts[8], 4);
    if (v2) {
        memcpy(out->pattern, &pts[10], 4);
    } else {
        out->pattern[0] = 0;
        out->pattern[1] = 0;
    }
    ok = true;
done:
    fclose(f);
    return ok;
}

// Decode a "PPAL" tint table into PSRAM. File is little-endian RGB565,
// which is native on the (little-endian) ESP32-S3 — read straight in.
static bool load_palette(const char *path, palette_t *out)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        return false;
    }
    uint8_t hdr[8];
    uint16_t *buf = NULL;
    bool ok = false;
    uint8_t entries = 0, ramp = 0;
    size_t n = 0;
    if (fread(hdr, 1, sizeof(hdr), f) != sizeof(hdr)) {
        goto done;
    }
    if (memcmp(hdr, PALETTE_MAGIC, 4) != 0 || hdr[4] != 1
        || hdr[5] == 0 || hdr[6] == 0) {
        ESP_LOGW(TAG, "%s: bad palette header", path);
        goto done;
    }
    entries = hdr[5];
    ramp = hdr[6];
    n = (size_t)entries * ramp;
    buf = heap_caps_malloc(n * sizeof(uint16_t), MALLOC_CAP_SPIRAM);
    if (!buf) {
        ESP_LOGE(TAG, "%s: PSRAM alloc failed", path);
        goto done;
    }
    if (fread(buf, sizeof(uint16_t), n, f) != n) {
        ESP_LOGW(TAG, "%s: short read", path);
        heap_caps_free(buf);
        buf = NULL;
        goto done;
    }
    out->entries = entries;
    out->ramp = ramp;
    out->rgb565 = buf;
    ok = true;
done:
    fclose(f);
    return ok;
}

static void free_sprites(void)
{
    for (int i = 0; i < LAYER_COUNT; i++) {
        if (s_sprites.layer[i].pixels) {
            heap_caps_free(s_sprites.layer[i].pixels);
        }
    }
    memset(&s_sprites, 0, sizeof(s_sprites));
}

void renderer_init(void)
{
    ESP_ERROR_CHECK(bsp_i2c_init());
    s_disp = bsp_display_start();
    if (s_disp == NULL) {
        ESP_LOGE(TAG, "bsp_display_start failed");
        return;
    }
    bsp_display_brightness_set(80);
    ESP_LOGI(TAG, "display + touch + LVGL up (%" PRId32 "x%" PRId32 ")",
             lv_display_get_horizontal_resolution(s_disp),
             lv_display_get_vertical_resolution(s_disp));

    // Mount the flash-resident sprite library read-only (architecture §2/§5).
    esp_vfs_littlefs_conf_t conf = {
        .base_path = ASSETS_BASE,
        .partition_label = ASSETS_LABEL,
        .format_if_mount_failed = false,
        .dont_mount = false,
    };
    esp_err_t e = esp_vfs_littlefs_register(&conf);
    if (e != ESP_OK) {
        ESP_LOGE(TAG, "assets LittleFS mount failed: %s",
                 esp_err_to_name(e));
        s_fs_ok = false;
    } else {
        size_t total = 0, used = 0;
        esp_littlefs_info(ASSETS_LABEL, &total, &used);
        ESP_LOGI(TAG, "assets mounted at %s (%u/%u bytes)",
                 ASSETS_BASE, (unsigned)used, (unsigned)total);
        s_fs_ok = true;

        if (!load_palette(ASSETS_BASE "/palettes/body.pal", &s_pal_body)) {
            ESP_LOGW(TAG, "body palette missing — body layers untinted");
        }
        if (!load_palette(ASSETS_BASE "/palettes/eye.pal", &s_pal_eye)) {
            ESP_LOGW(TAG, "eye palette missing — eyes untinted");
        }
    }
}

bool renderer_lock(uint32_t timeout_ms)
{
    return bsp_display_lock(timeout_ms);
}

void renderer_unlock(void)
{
    bsp_display_unlock();
}

bool renderer_load_pet_sprites(const Pet *pet)
{
    if (!s_fs_ok || pet == NULL) {
        return false;
    }
    if (pet->stage >= (sizeof(STAGE_DIR) / sizeof(STAGE_DIR[0]))) {
        ESP_LOGW(TAG, "stage %u out of range", pet->stage);
        return false;
    }
    free_sprites();
    const char *stage = STAGE_DIR[pet->stage];

    for (int L = 0; L < LAYER_COUNT; L++) {
        char layer_base[PATH_MAX_LEN];
        char shape[NAME_MAX + 1];
        char shape_dir[PATH_MAX_LEN];
        char sprite_path[PATH_MAX_LEN];

        snprintf(layer_base, sizeof(layer_base), "%s/%s/%s",
                 ASSETS_BASE, stage, LAYER_DIR[L]);
        if (!resolve_shape(layer_base, layer_gene_value(pet, L), shape)) {
            continue;  // no art for this layer — fine, skip
        }
        snprintf(shape_dir, sizeof(shape_dir), "%s/%s", layer_base, shape);
        if (!resolve_sprite_file(shape_dir, LAYER_ANIM[L], sprite_path)) {
            continue;
        }
        if (!load_sprite(sprite_path, &s_sprites.layer[L])) {
            ESP_LOGW(TAG, "layer %s: load %s failed",
                     LAYER_DIR[L], sprite_path);
            continue;
        }
        ESP_LOGI(TAG, "layer %s: %s (%ux%u x%u)", LAYER_DIR[L], sprite_path,
                 s_sprites.layer[L].hdr.width,
                 s_sprites.layer[L].hdr.height,
                 s_sprites.layer[L].hdr.num_frames);

        if (L == LAYER_BODY) {
            char anchors_path[PATH_MAX_LEN];
            snprintf(anchors_path, sizeof(anchors_path),
                     "%s/anchors.bin", shape_dir);
            if (!load_anchors(anchors_path, &s_sprites.anchors)) {
                ESP_LOGW(TAG, "body %s: no/invalid anchors.bin", shape);
            }
        }
    }

    if (s_sprites.layer[LAYER_BODY].pixels == NULL) {
        ESP_LOGE(TAG, "no body sprite for stage %s — nothing to draw",
                 stage);
        free_sprites();
        return false;
    }
    s_sprites.valid = true;
    return true;
}

const pet_sprites_t *renderer_pet_sprites(void)
{
    return s_sprites.valid ? &s_sprites : NULL;
}

const palette_t *renderer_palette_body(void)
{
    return s_pal_body.rgb565 ? &s_pal_body : NULL;
}

const palette_t *renderer_palette_eye(void)
{
    return s_pal_eye.rgb565 ? &s_pal_eye : NULL;
}

uint16_t renderer_gray_rgb565(uint8_t g)
{
    // Cast to uint32_t first: avoids signed-int promotion in the shifts and
    // makes byte-parity with forge_common.rgb565() explicit/portable.
    uint32_t v = g;
    return (uint16_t)(((v & 0xF8u) << 8) | ((v & 0xFCu) << 3) | (v >> 3));
}

uint16_t renderer_tint_rgb565(const palette_t *pal, uint8_t entry,
                              uint8_t gray)
{
    if (pal == NULL || pal->rgb565 == NULL
        || pal->entries == 0 || pal->ramp == 0) {
        return renderer_gray_rgb565(gray);
    }
    uint8_t shade = (uint8_t)(((uint32_t)gray * pal->ramp) >> 8);
    if (shade >= pal->ramp) {
        shade = pal->ramp - 1;
    }
    return pal->rgb565[(entry % pal->entries) * pal->ramp + shade];
}

// ---- Composition (build-order step 5 phase ④ + polish-gate "move") ----
//
// Back-to-front src-over alpha blend of the loaded, gene-tinted layers
// into an ARGB8888 buffer (LVGL needs per-pixel alpha). Each layer's
// frame index is `s_anim_frame % layer.num_frames`, so layers with
// different frame counts loop independently from a single global tick.
// Layers are placed body-relative: body & pattern at (0,0), upper layers
// at their PANC anchor. Out-of-canvas pixels are clipped.

static uint32_t *s_canvas;          // ARGB8888 (0xAARRGGBB), PSRAM
static int       s_canvas_w, s_canvas_h;
static lv_image_dsc_t s_pet_img;
static lv_obj_t *s_pet_obj;
static lv_obj_t *s_placeholder_obj;   // shown only on load/compose failure

// Animation state (polish-gate "move"). LVGL timer drives composition at
// ~5 fps per architecture §5.5. Latched Pet lets the timer re-compose
// without the caller's pointer needing to outlive renderer_draw_pet.
#define ANIM_PERIOD_MS 200          // 5 fps
static lv_timer_t *s_anim_timer;
static uint8_t     s_anim_frame;
static Pet         s_anim_pet;
static bool        s_anim_pet_valid;

// Pet movement state. Reactions and idle breathing oscillate around the
// base (x, y) captured at the most recent renderer_draw_pet call.
static int  s_pet_base_x;
static int  s_pet_base_y;
static bool s_movement_active;

static void start_idle_breathe(void);
// Wander loop — gentle horizontal pacing. Reactions on the X axis
// (wiggle/shake) pause it via these; the back-to-base callback resumes.
static void wander_pause(void);
static void wander_schedule_next(uint32_t delay_ms);

static void anim_back_to_base_y_cb(lv_anim_t *a)
{
    (void)a;
    if (!s_pet_obj) return;
    lv_obj_set_y(s_pet_obj, s_pet_base_y);
    start_idle_breathe();
}

static void anim_back_to_base_x_cb(lv_anim_t *a)
{
    (void)a;
    if (!s_pet_obj) return;
    lv_obj_set_x(s_pet_obj, s_pet_base_x);
    // Reaction is done — let the pet drift again after a short beat so
    // the user can register the reaction completing before the next
    // walk segment starts.
    wander_schedule_next(1200);
}

static void start_idle_breathe(void)
{
    if (!s_pet_obj) return;
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet_obj);
    lv_anim_set_values(&a, s_pet_base_y, s_pet_base_y - 3);
    lv_anim_set_duration(&a, 1100);
    lv_anim_set_playback_duration(&a, 1100);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_start(&a);
}

static void react_hop(void)
{
    if (!s_pet_obj) return;
    lv_anim_delete(s_pet_obj, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet_obj);
    lv_anim_set_values(&a, s_pet_base_y, s_pet_base_y - 14);
    lv_anim_set_duration(&a, 140);
    lv_anim_set_playback_duration(&a, 200);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_out);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_set_completed_cb(&a, anim_back_to_base_y_cb);
    lv_anim_start(&a);
}

static void react_wiggle(void)
{
    if (!s_pet_obj) return;
    // Wiggle and walk both animate X — pause the wander loop, then
    // re-anchor base_x to the pet's live position so the reaction's
    // back-to-base doesn't warp the pet to a stale walk target.
    wander_pause();
    lv_anim_delete(s_pet_obj, (lv_anim_exec_xcb_t)lv_obj_set_x);
    s_pet_base_x = lv_obj_get_x(s_pet_obj);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet_obj);
    lv_anim_set_values(&a, s_pet_base_x - 6, s_pet_base_x + 6);
    lv_anim_set_duration(&a, 120);
    lv_anim_set_playback_duration(&a, 120);
    lv_anim_set_repeat_count(&a, 3);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_completed_cb(&a, anim_back_to_base_x_cb);
    lv_anim_start(&a);
}

static void react_shake(void)
{
    if (!s_pet_obj) return;
    wander_pause();
    lv_anim_delete(s_pet_obj, (lv_anim_exec_xcb_t)lv_obj_set_x);
    s_pet_base_x = lv_obj_get_x(s_pet_obj);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet_obj);
    lv_anim_set_values(&a, s_pet_base_x - 4, s_pet_base_x + 4);
    lv_anim_set_duration(&a, 55);
    lv_anim_set_playback_duration(&a, 55);
    lv_anim_set_repeat_count(&a, 7);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_completed_cb(&a, anim_back_to_base_x_cb);
    lv_anim_start(&a);
}

void renderer_pet_react(pet_reaction_t kind)
{
    switch (kind) {
    case REACT_HOP:    react_hop();    break;
    case REACT_WIGGLE: react_wiggle(); break;
    case REACT_SHAKE:  react_shake();  break;
    case REACT_NONE:
    default:           break;
    }
}

// ---- Wander (gentle horizontal pacing on the floor) ------------------
//
// A repeating walk loop so the scene doesn't feel like a static portrait.
// One LVGL timer schedules the next walk; one LVGL anim drives the X
// translation. Plays on top of the breathing anim (which owns Y) — the
// two are tracked independently by LVGL so they never collide.
//
// Bounds are in *object-space X*. The visual pet extends ~32 px left
// and ~96 px right of its LVGL object X because the body PNG is a
// 64-px box rendered at 2x via centre-pivot scaling. The range below
// keeps the visual within the 24-px safe-area inset on the 368-px
// wide AMOLED. If the scene layout changes (e.g. a side panel), bump
// the constants here rather than threading bounds through the API.
#define WANDER_MIN_X         56
#define WANDER_MAX_X        240
#define WANDER_STEP_MIN_MS  2000
#define WANDER_STEP_MAX_MS  3500
#define WANDER_PAUSE_MIN_MS 1500
#define WANDER_PAUSE_MAX_MS 3500
// Reject targets closer than this to the current position — a 12-px
// drift over 2.5 s reads as "twitch", not "walk".
#define WANDER_MIN_DELTA     40

static lv_timer_t *s_wander_timer;

static uint32_t wander_random_in(uint32_t lo, uint32_t hi)
{
    if (hi <= lo) return lo;
    return lo + (esp_random() % (hi - lo + 1));
}

static void wander_step_cb(lv_timer_t *t);

// Re-arm the wander timer to fire ONCE after `delay_ms`. Idempotent: a
// repeated call just re-periods the existing timer instead of stacking
// new ones. This is the only entry point for kicking off (or resuming)
// the wander loop, so callers don't need to know whether a timer exists.
static void wander_schedule_next(uint32_t delay_ms)
{
    if (s_wander_timer == NULL) {
        s_wander_timer = lv_timer_create(wander_step_cb, delay_ms, NULL);
        lv_timer_set_repeat_count(s_wander_timer, 1);
        return;
    }
    lv_timer_set_period(s_wander_timer, delay_ms);
    lv_timer_set_repeat_count(s_wander_timer, 1);
    lv_timer_reset(s_wander_timer);
    lv_timer_resume(s_wander_timer);
}

static void wander_pause(void)
{
    if (s_wander_timer) lv_timer_pause(s_wander_timer);
}

static void wander_complete_cb(lv_anim_t *a)
{
    (void)a;
    wander_schedule_next(wander_random_in(WANDER_PAUSE_MIN_MS,
                                          WANDER_PAUSE_MAX_MS));
}

static void wander_step_cb(lv_timer_t *t)
{
    (void)t;
    // One-shot timer (repeat_count=1) — LVGL auto-deletes it right after
    // this callback returns. Null our tracking pointer NOW so reactions
    // and wander_schedule_next don't dereference a freed timer if they
    // run before the next start_wander/wander_schedule_next replaces it.
    // (Same pattern as emote_dismiss_cb above.)
    s_wander_timer = NULL;
    if (s_pet_obj == NULL) return;
    int cur_x  = lv_obj_get_x(s_pet_obj);
    int target = (int)wander_random_in(WANDER_MIN_X, WANDER_MAX_X);
    int delta  = target > cur_x ? target - cur_x : cur_x - target;
    if (delta < WANDER_MIN_DELTA) {
        // Too close to register as a walk — bounce to the opposite half
        // so the user always sees motion when the timer fires.
        target = (cur_x > (WANDER_MIN_X + WANDER_MAX_X) / 2)
                 ? WANDER_MIN_X : WANDER_MAX_X;
    }
    s_pet_base_x = target;     // reactions use this as their anchor
    uint32_t duration = wander_random_in(WANDER_STEP_MIN_MS,
                                          WANDER_STEP_MAX_MS);
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_pet_obj);
    lv_anim_set_values(&a, cur_x, target);
    lv_anim_set_duration(&a, duration);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_in_out);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_x);
    lv_anim_set_completed_cb(&a, wander_complete_cb);
    lv_anim_start(&a);
}

// Called once from renderer_draw_pet after the initial layout. A 2-s
// initial delay lets the pet "settle" at its starting position before
// the first walk fires so boot-up doesn't look frantic.
static void start_wander(void)
{
    wander_schedule_next(2000);
}

// ---- Emote bubble overlay (architecture §7.4) ------------------------
//
// One slot, one LVGL image, one one-shot timer. A new renderer_show_emote
// replaces the previous bubble outright — no queue. The 48-px Kenney
// bubble sits ~60 px above the pet's base Y and 8 px to its right, so
// the bubble's tail points down at the pet's head and the glyph never
// covers the pet's face. The lookup table mirrors emote_id_t in ui.h;
// IDs without art fall through to "no emote", which simply hides any
// in-flight bubble.

static lv_obj_t   *s_emote_obj;
static lv_timer_t *s_emote_timer;

// emote_id_t -> bubble image. Sparse: only the IDs we currently have art
// for are populated; the rest stay NULL and the request becomes a no-op
// (after dismissing any active bubble). Indices match the enum values
// in firmware/components/ui/include/ui.h:
//   2  = EMOTE_AFFECTION (heart bubble)
//   3  = EMOTE_EXCITED   (star bubble)
//   10 = EMOTE_HUNGRY    (exclamation — urgent need from mood logic)
//   11 = EMOTE_SLEEPY    (zzz bubble)
//   12 = EMOTE_THIRSTY   (drop bubble)
//   22 = EMOTE_CONFUSED  (question — curious personality ambient)
//   25 = EMOTE_SAD       (sad face — mood logic for very low stats)
// Extend in lockstep when adding renderer_emote_* slots to the
// converter. Sized to cover the full wire range (0..32) so adding new
// IDs is just a designated-initializer line, never a table resize.
#define EMOTE_TABLE_SIZE 33
static const lv_image_dsc_t *const s_emote_imgs[EMOTE_TABLE_SIZE] = {
    [2]  = &renderer_emote_affection_img,
    [3]  = &renderer_emote_excited_img,
    [10] = &renderer_emote_hungry_img,
    [11] = &renderer_emote_sleepy_img,
    [12] = &renderer_emote_thirsty_img,
    [22] = &renderer_emote_confused_img,
    [25] = &renderer_emote_sad_img,
};

// Pixel offset of the bubble's top-left from the pet's base (x, y).
// Positive X moves the bubble right of the pet; negative Y moves it up.
// Tuned so the bubble's downward-pointing tail sits just above the pet
// head silhouette at the current ~128 px rendered pet size.
#define EMOTE_OFFSET_X   8
#define EMOTE_OFFSET_Y (-60)

static void emote_clear(void)
{
    if (s_emote_obj)   { lv_obj_del(s_emote_obj);   s_emote_obj   = NULL; }
    if (s_emote_timer) { lv_timer_del(s_emote_timer); s_emote_timer = NULL; }
}

static void emote_dismiss_cb(lv_timer_t *t)
{
    (void)t;
    // Timer fired => it self-destructs after this returns. Null the
    // pointer first so emote_clear() doesn't try to delete it twice if
    // a new renderer_show_emote arrives mid-callback.
    s_emote_timer = NULL;
    if (s_emote_obj) { lv_obj_del(s_emote_obj); s_emote_obj = NULL; }
}

void renderer_show_emote(uint8_t emote_id, uint32_t duration_ms)
{
    emote_clear();   // single-slot — drop any in-flight bubble first
    if (emote_id >= EMOTE_TABLE_SIZE) {
        return;
    }
    const lv_image_dsc_t *img = s_emote_imgs[emote_id];
    if (img == NULL) {
        return;     // no art for this ID yet — silently no-op
    }
    if (s_pet_obj == NULL) {
        return;     // no pet on screen to anchor against
    }

    s_emote_obj = lv_image_create(lv_screen_active());
    lv_image_set_src(s_emote_obj, img);
    lv_image_set_antialias(s_emote_obj, false);
    // Anchor X to the pet's LIVE position — s_pet_base_x is the walk
    // target, which lags the pet mid-step. Y still tracks the base
    // since breathing only oscillates 3 px, invisible at this scale.
    lv_obj_set_pos(s_emote_obj,
                   lv_obj_get_x(s_pet_obj) + EMOTE_OFFSET_X,
                   s_pet_base_y + EMOTE_OFFSET_Y);

    s_emote_timer = lv_timer_create(emote_dismiss_cb, duration_ms, NULL);
    lv_timer_set_repeat_count(s_emote_timer, 1);
}

// Tap-the-pet handler — same primitive as a feed-hop; rewards user for
// poking at the toy. Discoverable via finger; no on-screen affordance
// needed (the pet itself is the affordance).
static void pet_tap_cb(lv_event_t *e)
{
    (void)e;
    react_hop();
}

static void anchor_for(const pet_sprites_t *ps, int layer,
                       int *ox, int *oy)
{
    *ox = 0;
    *oy = 0;
    switch (layer) {
    case LAYER_EYES:    *ox = ps->anchors.eyes[0];    *oy = ps->anchors.eyes[1];    break;
    case LAYER_MOUTH:   *ox = ps->anchors.mouth[0];   *oy = ps->anchors.mouth[1];   break;
    case LAYER_EARS:    *ox = ps->anchors.ears[0];    *oy = ps->anchors.ears[1];    break;
    case LAYER_TAIL:    *ox = ps->anchors.tail[0];    *oy = ps->anchors.tail[1];    break;
    case LAYER_PATTERN: *ox = ps->anchors.pattern[0]; *oy = ps->anchors.pattern[1]; break;
    case LAYER_ACCESSORY:
        *ox = ps->anchors.accessory[0]; *oy = ps->anchors.accessory[1]; break;
    default: break;  // BODY -> (0,0)
    }
}

// Per architecture §5.1: body/tail/ears/pattern use the body_color tint;
// eyes use eye_color; mouth/accessory are untinted (gray).
static const palette_t *tint_for(int layer, const Pet *pet, uint8_t *entry)
{
    switch (layer) {
    case LAYER_EYES:
        *entry = pet->genes[GENE_EYE_COLOR];
        return renderer_palette_eye();
    case LAYER_BODY:
    case LAYER_TAIL:
    case LAYER_EARS:
    case LAYER_PATTERN:
        *entry = pet->genes[GENE_BODY_COLOR];
        return renderer_palette_body();
    default:                  // mouth, accessory
        *entry = 0;
        return NULL;
    }
}

static bool compose_pet(const Pet *pet)
{
    const pet_sprites_t *ps = renderer_pet_sprites();
    if (!ps || !ps->layer[LAYER_BODY].pixels) {
        return false;
    }
    const int W = ps->layer[LAYER_BODY].hdr.width;
    const int H = ps->layer[LAYER_BODY].hdr.height;
    const size_t npx = (size_t)W * H;

    if (s_canvas == NULL || s_canvas_w != W || s_canvas_h != H) {
        if (s_canvas) {
            heap_caps_free(s_canvas);
            // The old buffer is gone — make sure no stale LVGL render can
            // dereference it via s_pet_img if we fail below.
            s_pet_img.data = NULL;
            s_pet_img.data_size = 0;
        }
        s_canvas = heap_caps_malloc(npx * 4, MALLOC_CAP_SPIRAM);
        if (!s_canvas) {
            s_canvas_w = s_canvas_h = 0;
            return false;
        }
        s_canvas_w = W;
        s_canvas_h = H;
    }
    memset(s_canvas, 0, npx * 4);   // fully transparent

    // Pre-compute pointer to the body's current frame so the pattern
    // layer can mask itself against body alpha without re-resolving the
    // body sprite per pixel. Body draws at canvas (0, 0) so its pixel
    // coordinate space == canvas coordinate space.
    const sprite_t *body_sp  = &ps->layer[LAYER_BODY];
    const uint8_t   body_bpp = format_bpp(body_sp->hdr.format);
    const uint8_t   body_nf  = body_sp->hdr.num_frames ? body_sp->hdr.num_frames : 1;
    const uint8_t   body_fi  = s_anim_frame % body_nf;
    const uint8_t  *body_fr  = body_sp->pixels +
        (size_t)body_fi * body_sp->hdr.width * body_sp->hdr.height * body_bpp;

    for (int L = 0; L < LAYER_COUNT; L++) {       // back -> front
        const sprite_t *s = &ps->layer[L];
        if (!s->pixels) {
            continue;
        }
        int ox, oy;
        anchor_for(ps, L, &ox, &oy);
        uint8_t entry;
        const palette_t *pal = tint_for(L, pet, &entry);
        const int sw = s->hdr.width, sh = s->hdr.height;
        // Per-layer frame: each layer loops at its own length from the
        // shared s_anim_frame, so 2-frame body and 4-frame blink coexist.
        const uint8_t bpp = format_bpp(s->hdr.format);
        const uint8_t nf  = s->hdr.num_frames ? s->hdr.num_frames : 1;
        const uint8_t fi  = s_anim_frame % nf;
        const uint8_t *fr = s->pixels + (size_t)fi * sw * sh * bpp;

        for (int yy = 0; yy < sh; yy++) {
            int cy = oy + yy;
            if (cy < 0 || cy >= H) {
                continue;
            }
            for (int xx = 0; xx < sw; xx++) {
                int cx = ox + xx;
                if (cx < 0 || cx >= W) {
                    continue;
                }
                const uint8_t *p = fr + ((size_t)yy * sw + xx) * 2;
                uint8_t gray = p[0], a = p[1];
                if (a == 0) {
                    continue;
                }
                // Pattern decoration is painted ON the body — clip it
                // to the body's silhouette so stripes/spots can't leak
                // into transparent canvas areas around the body. Body
                // is at canvas (0,0) so (cx, cy) IS the body pixel.
                if (L == LAYER_PATTERN) {
                    uint8_t body_a = body_fr[((size_t)cy * body_sp->hdr.width + cx)
                                             * body_bpp + 1];
                    if (body_a == 0) {
                        continue;
                    }
                }
                uint16_t c = pal ? renderer_tint_rgb565(pal, entry, gray)
                                 : renderer_gray_rgb565(gray);
                uint8_t r = (c >> 8) & 0xF8; r |= r >> 5;
                uint8_t g = (c >> 3) & 0xFC; g |= g >> 6;
                uint8_t b = (c << 3) & 0xF8; b |= b >> 5;

                uint32_t *dst = &s_canvas[(size_t)cy * W + cx];
                uint32_t d = *dst;
                uint8_t da = (d >> 24) & 0xFF;
                if (a == 255 || da == 0) {
                    *dst = ((uint32_t)a << 24) | ((uint32_t)r << 16)
                         | ((uint32_t)g << 8) | b;
                } else {
                    // Straight-alpha src-over with a semi-transparent dst:
                    //   oa = a + da*(1-a)              (<=255 for valid a)
                    //   out = (src*a + dst*da*(1-a)) / oa
                    // Weighting dst by da and dividing by oa (not 255) is
                    // required, else colours go too dark at AA edges.
                    uint32_t ia = 255u - a;
                    uint8_t dr = (d >> 16) & 0xFF;
                    uint8_t dg = (d >> 8) & 0xFF;
                    uint8_t db = d & 0xFF;
                    uint32_t dw = (uint32_t)da * ia / 255u;   // dst weight
                    uint32_t oa = (uint32_t)a + dw;
                    if (oa == 0) {
                        *dst = 0;
                    } else {
                        uint8_t orr = (uint8_t)(((uint32_t)r * a + dr * dw) / oa);
                        uint8_t og  = (uint8_t)(((uint32_t)g * a + dg * dw) / oa);
                        uint8_t ob  = (uint8_t)(((uint32_t)b * a + db * dw) / oa);
                        *dst = (oa << 24) | ((uint32_t)orr << 16)
                             | ((uint32_t)og << 8) | ob;
                    }
                }
            }
        }
    }
    return true;
}

// LVGL timer callback — advance frame, re-compose into s_canvas, invalidate
// the LVGL image so it redraws. Runs on the LVGL task under its mutex, so
// it serializes naturally with renderer_draw_pet (which holds the same
// mutex via renderer_lock). No-op until renderer_draw_pet has latched a
// pet and built the image object.
static void anim_tick(lv_timer_t *t)
{
    (void)t;
    if (!s_anim_pet_valid || s_pet_obj == NULL || s_canvas == NULL) {
        return;
    }
    s_anim_frame++;
    if (!compose_pet(&s_anim_pet)) {
        return;
    }
    lv_obj_invalidate(s_pet_obj);
}

void renderer_draw_pet(const Pet *pet, int x, int y)
{
    if (pet == NULL) {
        return;
    }
    if (renderer_pet_sprites() == NULL) {
        renderer_load_pet_sprites(pet);
    }
    if (!compose_pet(pet)) {
        // Load/compose failed (e.g. assets not flashed yet). Show ONE
        // reusable placeholder — never leak a new lv_obj per call.
        if (s_pet_obj) {
            lv_obj_del(s_pet_obj);
            s_pet_obj = NULL;
        }
        if (s_placeholder_obj == NULL) {
            s_placeholder_obj = lv_obj_create(lv_screen_active());
            lv_obj_set_size(s_placeholder_obj, 128, 128);
            lv_obj_set_style_radius(s_placeholder_obj, LV_RADIUS_CIRCLE, 0);
            lv_obj_set_style_bg_color(s_placeholder_obj,
                                      lv_color_hex(0xf5d76e), 0);
            lv_obj_set_style_border_width(s_placeholder_obj, 0, 0);
        }
        lv_obj_set_pos(s_placeholder_obj, x, y);
        return;
    }
    if (s_placeholder_obj) {            // compose succeeded — drop fallback
        lv_obj_del(s_placeholder_obj);
        s_placeholder_obj = NULL;
    }

    s_pet_img.header.magic  = LV_IMAGE_HEADER_MAGIC;
    s_pet_img.header.cf     = LV_COLOR_FORMAT_ARGB8888;
    s_pet_img.header.w      = s_canvas_w;
    s_pet_img.header.h      = s_canvas_h;
    s_pet_img.header.stride = s_canvas_w * 4;
    s_pet_img.data          = (const uint8_t *)s_canvas;
    s_pet_img.data_size     = (uint32_t)s_canvas_w * s_canvas_h * 4;

    if (s_pet_obj == NULL) {
        s_pet_obj = lv_image_create(lv_screen_active());
        lv_image_set_antialias(s_pet_obj, false);  // crisp pixel art
        // Make the pet itself tappable. LVGL images aren't clickable by
        // default — this is what wires up the "tap the pet to make it hop".
        lv_obj_add_flag(s_pet_obj, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_add_event_cb(s_pet_obj, pet_tap_cb, LV_EVENT_CLICKED, NULL);
    }
    lv_image_set_src(s_pet_obj, &s_pet_img);
    if (s_canvas_w > 0) {                           // ~64 -> ~128 (§5.4)
        lv_image_set_scale(s_pet_obj, (256 * 128) / s_canvas_w);
    }
    s_pet_base_x = x;
    s_pet_base_y = y;
    lv_obj_set_pos(s_pet_obj, x, y);

    // Restart idle breathing around the new base position. lv_anim_delete
    // first so a previous run from an old base doesn't keep oscillating
    // against stale coordinates.
    lv_anim_delete(s_pet_obj, (lv_anim_exec_xcb_t)lv_obj_set_y);
    start_idle_breathe();
    // Reset the wander loop too — a re-draw (e.g. evolution stage change
    // later) should kick off pacing fresh from the new spawn position
    // rather than inheriting a stale walk target.
    if (s_wander_timer) { lv_timer_del(s_wander_timer); s_wander_timer = NULL; }
    start_wander();
    s_movement_active = true;

    // Latch a Pet snapshot for the animation timer to re-compose from.
    // Pet is small (< 256 B per architecture §4.1) so the copy is cheap.
    s_anim_pet       = *pet;
    s_anim_pet_valid = true;
    if (s_anim_timer == NULL) {
        s_anim_timer = lv_timer_create(anim_tick, ANIM_PERIOD_MS, NULL);
    }
}
