# Generated by scripts/generate_pet_characters.py
CHARACTERS = [{'key': 'sprout',
  'name': 'Sprout',
  'description': 'A sunny little sprout with two green leaves.',
  'appearance': 'A buttery-yellow pear-shaped sprout creature with green leaves and rosy cheeks.'},
 {'key': 'bunny',
  'name': 'Cloud bunny',
  'description': 'A soft cloud bunny with one floppy ear.',
  'appearance': 'A cream-white round bunny with pink-lined ears, one folded ear tip and a little '
                'round tail.'},
 {'key': 'penguin',
  'name': 'Pebble penguin',
  'description': 'A little blue penguin with tiny flippers.',
  'appearance': 'A sky-blue round penguin with a cream face and tummy, little blue head feather '
                'and orange feet.'},
 {'key': 'kitten',
  'name': 'Peach kitten',
  'description': 'A peachy kitten with stripes and a curly tail.',
  'appearance': 'A peach-orange kitten with triangular ears, cream muzzle and tummy, cinnamon '
                'stripes and a curled tail.'},
 {'key': 'dragon',
  'name': 'Tiny dragon',
  'description': 'A gentle little dragon with tiny wings.',
  'appearance': 'A lavender baby dragon with tiny ivory horns, mint belly, little wings and a '
                'curved spiky tail.'},
 {'key': 'pig',
  'name': 'Rosy pig',
  'description': 'A pink little pig in a bright red dress.',
  'appearance': 'A pink pig with a rounded snout, two upright ears, rosy cheeks, a curly tail, a '
                'bright red dress and little dark shoes.'},
 {'key': 'larry',
  'name': 'Larry',
  'description': 'An ordinary salaryman on his lunch break.',
  'appearance': 'A miniature adult salaryman with tired half-lidded eyes, swept dark hair with '
                'silver streaks, a charcoal business suit, a pale shirt, a blue cloud-pattern tie '
                'and dark shoes.',
  'voice_style': 'Quiet, understated and gently dry, like a salaryman enjoying a well-earned lunch '
                 'break. Occasional small jokes about meetings, paperwork or taking a break; still '
                 'warm and kind. Never sound like a corporate assistant or be dismissive.'}]
