// Generated by scripts/generate_pet_characters.py.
#pragma once
static const pet_character_t CHARACTERS[PET_CHARACTER_COUNT] = {
{"Sprout","A sunny little sprout with two green leaves."},
{"Cloud bunny","A soft cloud bunny with one floppy ear."},
{"Pebble penguin","A little blue penguin with tiny flippers."},
{"Peach kitten","A peachy kitten with stripes and a curly tail."},
{"Tiny dragon","A gentle little dragon with tiny wings."},
};
