#!/usr/bin/env python3
"""Pack the Kenney emote bubble glyphs into a single LVGL C header.

Each emote ships at 16×16 with its speech bubble already drawn in —
unlike the naked stat icons (ui_icons.h), these are meant to appear
*above* the pet as a thought/utterance, so the bubble outline reads
correctly. We integer-upscale 3× → 48×48 using NEAREST sampling to
keep pixel-art crisp at the AMOLED's 322 ppi.

Sources live in sprite_forge/emotes/kenney_emotes-pack/PNG/Pixel/Style 1
(the style used by ui_icons.h's hand-drawn variants for visual
consistency). Style 1 is the chunkiest of the eight Kenney styles and
matches the stroke weight of our chrome.

Output: firmware/components/renderer/include/renderer_emotes.h — an
`renderer_emote_<slot>_img` lv_image_dsc_t per emote, ARGB8888
little-endian BGRA byte order (same encoding as ui_icons.h /
ui_buttons.h). The header lives in the renderer (not the ui) component
because the renderer owns the bubble overlay and dispatches emote IDs
to images; ui would create a circular component dependency.

Re-run after changing any source PNG. The generated header IS committed
so fresh checkouts build without running this script first.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ModuleNotFoundError:
    sys.exit("Pillow not installed — run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = (ROOT / "sprite_forge" / "emotes" / "kenney_emotes-pack"
           / "PNG" / "Pixel" / "Style 1")
OUT = (ROOT / "firmware" / "components" / "renderer" / "include"
       / "renderer_emotes.h")

# Slot name -> Kenney PNG stem. Slot names map 1:1 onto the renderer's
# emote_id_t enum entries (see firmware/components/ui/include/ui.h).
# Start with the four bubbles needed by the care actions; extend as
# more emote_id_t entries get wired up (mood reactions, idle ambient,
# need-threshold signals, etc.).
EMOTES = [
    ("affection", "emote_heart"),
    ("excited",   "emote_star"),
    ("sleepy",    "emote_sleep"),
    ("thirsty",   "emote_drop"),
    # Mood-feedback bubbles driven by pet_state_mood_emote() — fired
    # autonomously when needs cross thresholds (architecture §7.5).
    ("hungry",    "emote_exclamation"),    # "!" — urgent need
    ("sad",       "emote_faceSad"),
    ("confused",  "emote_question"),       # "?" — for personality ambient
]

OUT_SIZE = 48   # 3× the 16-px source; NEAREST keeps pixel edges crisp


def png_to_argb8888(path: Path, size: int) -> tuple[int, int, bytes]:
    """Load source PNG and emit ARGB8888 at size×size after NEAREST upscale.

    Kenney emotes are already centred in their 16-px frame and include
    the bubble outline + glyph at the intended composition. So unlike
    icons_to_c.py we deliberately skip bbox-normalisation here — the
    transparent margin around the bubble IS part of the asset and
    keeps multiple emotes visually aligned with each other.
    """
    img = Image.open(path).convert("RGBA")
    if img.size != (size, size):
        img = img.resize((size, size), Image.Resampling.NEAREST)

    rgba = img.tobytes()
    out = bytearray(size * size * 4)
    for i in range(size * size):
        # LVGL ARGB8888 is uint32_t little-endian => bytes B, G, R, A.
        out[i * 4 + 0] = rgba[i * 4 + 2]
        out[i * 4 + 1] = rgba[i * 4 + 1]
        out[i * 4 + 2] = rgba[i * 4 + 0]
        out[i * 4 + 3] = rgba[i * 4 + 3]
    return size, size, bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_data[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(f, name: str, w: int, h: int) -> None:
    f.write(f"static const lv_image_dsc_t {name}_img = {{\n")
    f.write("    .header = {\n")
    f.write("        .magic  = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("        .cf     = LV_COLOR_FORMAT_ARGB8888,\n")
    f.write(f"        .w      = {w},\n")
    f.write(f"        .h      = {h},\n")
    f.write(f"        .stride = {w * 4},\n")
    f.write("    },\n")
    f.write(f"    .data      = {name}_data,\n")
    f.write(f"    .data_size = sizeof({name}_data),\n")
    f.write("};\n\n")


def main() -> int:
    for _, stem in EMOTES:
        src = SRC_DIR / f"{stem}.png"
        if not src.exists():
            sys.exit(f"missing {src}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    with OUT.open("w") as f:
        f.write("// Generated by sprite_forge/emotes_to_c.py — do not edit by hand.\n")
        f.write("// Sources: kenney_emotes-pack/PNG/Pixel/Style 1/*.png\n")
        f.write("//          upscaled 3x (NEAREST) to 48x48 for crisp pixels.\n\n")
        f.write("#pragma once\n#include \"lvgl.h\"\n\n")
        for slot, stem in EMOTES:
            name = f"renderer_emote_{slot}"
            src = SRC_DIR / f"{stem}.png"
            w, h, data = png_to_argb8888(src, OUT_SIZE)
            f.write(emit_byte_array(name, data))
            f.write("\n\n")
            emit_dsc(f, name, w, h)
            total += len(data)
    print(f"wrote {OUT} ({len(EMOTES)} emotes, {total} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
