#!/usr/bin/env python3
"""Pack the UI icon set into a single LVGL C header.

Four glyphs cover all four needs. Each is emitted at two sizes (16 px
for the stat strip, 32 px for the care-action dock) so LVGL never has
to scale at runtime — pixel-art reads crispest at integer scales.

Sources:
  - sprite_forge/items/apple.png                          -> hunger
  - kenney_emotes-pack/PNG/Pixel/Style 1/emote_heart.png  -> happiness
  - kenney_emotes-pack/PNG/Pixel/Style 1/emote_sleep.png  -> energy
  - kenney_emotes-pack/PNG/Pixel/Style 1/emote_drop.png   -> hygiene

Output:
  firmware/components/ui/include/ui_icons.h

Re-run after changing any source PNG. The generated header IS committed
so fresh checkouts build without running this script first.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ModuleNotFoundError:
    sys.exit("Pillow not installed — run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
ITEMS = ROOT / "sprite_forge" / "items"
UI_DIR = ROOT / "sprite_forge" / "ui"
OUT = ROOT / "firmware" / "components" / "ui" / "include" / "ui_icons.h"

# (slot, source path) — slot order matches enum/array order in ui.c.
# Heart / zzz / drop are hand-drawn via Piskel because the Kenney emote
# pack ships them inside speech bubbles, which reads as "emoji caption"
# rather than "stat icon" when sitting on the care dock.
ICONS = [
    ("hunger",    ITEMS  / "apple.png"),
    ("happiness", UI_DIR / "icon_heart.png"),
    ("energy",    UI_DIR / "icon_sleep.png"),
    ("hygiene",   UI_DIR / "icon_drop.png"),
]

SIZES = [32, 64]   # px — stat strip / care dock
CONTENT_RATIO = 0.85  # fraction of target frame the visible content fills


def png_to_argb8888(path: Path, size: int) -> tuple[int, int, bytes]:
    """Normalise source PNG and emit ARGB8888 at size×size.

    Different source packs (our food items vs. Kenney emotes) ship with
    very different transparent-padding conventions: apple fills ~75 % of
    its 32 px canvas; emotes are ~10 px content in a 16 px frame, often
    visually top- or bottom-aligned. Treating them as-is makes the apple
    look bigger and the emotes float to one side. To get a consistent
    visible size and centring:

      1. Crop to the alpha bbox (drops any padding).
      2. Scale the cropped content so its longer edge = CONTENT_RATIO ×
         size (NEAREST resampling — accepts non-integer scale artifacts
         in exchange for pixel-art crispness; bilinear would smudge).
      3. Paste the scaled content centred into a fresh size×size frame.

    Result: every glyph has the same visible-content size and is
    geometrically centred, regardless of where the original PNG put it.
    """
    img = Image.open(path).convert("RGBA")
    bbox = img.getchannel("A").getbbox()
    if bbox:
        img = img.crop(bbox)
    w, h = img.size
    content_max = max(1, int(size * CONTENT_RATIO))
    scale = min(content_max / max(w, 1), content_max / max(h, 1))
    new_w = max(1, round(w * scale))
    new_h = max(1, round(h * scale))
    scaled = img.resize((new_w, new_h), Image.Resampling.NEAREST)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.paste(scaled, ((size - new_w) // 2, (size - new_h) // 2))

    rgba = canvas.tobytes()
    out = bytearray(size * size * 4)
    for i in range(size * size):
        # LVGL ARGB8888 is uint32_t little-endian => bytes B, G, R, A.
        out[i * 4 + 0] = rgba[i * 4 + 2]
        out[i * 4 + 1] = rgba[i * 4 + 1]
        out[i * 4 + 2] = rgba[i * 4 + 0]
        out[i * 4 + 3] = rgba[i * 4 + 3]
    return size, size, bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_data[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_dsc(f, name: str, w: int, h: int):
    f.write(f"static const lv_image_dsc_t {name}_img = {{\n")
    f.write("    .header = {\n")
    f.write("        .magic  = LV_IMAGE_HEADER_MAGIC,\n")
    f.write("        .cf     = LV_COLOR_FORMAT_ARGB8888,\n")
    f.write(f"        .w      = {w},\n")
    f.write(f"        .h      = {h},\n")
    f.write(f"        .stride = {w * 4},\n")
    f.write("    },\n")
    f.write(f"    .data      = {name}_data,\n")
    f.write(f"    .data_size = sizeof({name}_data),\n")
    f.write("};\n\n")


def main() -> int:
    for _, path in ICONS:
        if not path.exists():
            sys.exit(f"missing {path}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    with OUT.open("w") as f:
        f.write("// Generated by sprite_forge/icons_to_c.py — do not edit by hand.\n")
        f.write("// Sources: items/apple.png + kenney_emotes-pack Style 1\n")
        f.write("//          (emote_heart.png / emote_sleep.png / emote_drop.png).\n\n")
        f.write("#pragma once\n#include \"lvgl.h\"\n\n")
        for slot, src in ICONS:
            for size in SIZES:
                name = f"ui_icon_{slot}_{size}"
                w, h, data = png_to_argb8888(src, size)
                f.write(emit_byte_array(name, data))
                f.write("\n\n")
                emit_dsc(f, name, w, h)
                total += len(data)
    print(f"wrote {OUT} ({len(ICONS) * len(SIZES)} variants, {total} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
