#!/usr/bin/env python3
"""Convert sprite_forge/items/*.png into an LVGL C-source food library.

Output: firmware/components/ui/include/food_items.h — embeds each PNG as a
`lv_image_dsc_t` in LV_COLOR_FORMAT_ARGB8888 plus a `food_items[]` table
the UI iterates over.

Re-run after editing any items/*.png. The generated header IS committed
so a fresh `idf.py build` doesn't depend on running this script first.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ModuleNotFoundError:
    sys.exit("Pillow not installed — run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
ITEMS_DIR = ROOT / "sprite_forge" / "items"
OUT = ROOT / "firmware" / "components" / "ui" / "include" / "food_items.h"

# Stable ordering — the UI references by index.
ITEM_NAMES = ["apple", "banana", "cake", "orange", "pear"]


def png_to_argb8888(path: Path) -> tuple[int, int, bytes]:
    """Read RGBA PNG, return (w, h, little-endian ARGB8888 bytes)."""
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    rgba = img.tobytes()
    out = bytearray(w * h * 4)
    for i in range(w * h):
        # LVGL ARGB8888 is uint32_t little-endian => bytes B, G, R, A.
        out[i * 4 + 0] = rgba[i * 4 + 2]
        out[i * 4 + 1] = rgba[i * 4 + 1]
        out[i * 4 + 2] = rgba[i * 4 + 0]
        out[i * 4 + 3] = rgba[i * 4 + 3]
    return w, h, bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_data[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    items = []
    for name in ITEM_NAMES:
        p = ITEMS_DIR / f"{name}.png"
        if not p.exists():
            sys.exit(f"missing {p}")
        items.append((name, *png_to_argb8888(p)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("// Generated by sprite_forge/items_to_c.py — do not edit by hand.\n")
        f.write("// Re-run after changing any sprite_forge/items/*.png.\n\n")
        f.write("#pragma once\n#include \"lvgl.h\"\n\n")
        for name, w, h, data in items:
            f.write(emit_byte_array(name, data))
            f.write("\n\n")
            f.write(f"static const lv_image_dsc_t food_{name}_img = {{\n")
            f.write("    .header = {\n")
            f.write("        .magic  = LV_IMAGE_HEADER_MAGIC,\n")
            f.write("        .cf     = LV_COLOR_FORMAT_ARGB8888,\n")
            f.write(f"        .w      = {w},\n")
            f.write(f"        .h      = {h},\n")
            f.write(f"        .stride = {w * 4},\n")
            f.write("    },\n")
            f.write(f"    .data      = {name}_data,\n")
            f.write(f"    .data_size = sizeof({name}_data),\n")
            f.write("};\n\n")
        f.write(f"#define FOOD_ITEM_COUNT {len(items)}\n\n")
        f.write("typedef struct {\n")
        f.write("    const char *name;\n")
        f.write("    const lv_image_dsc_t *img;\n")
        f.write("} food_item_t;\n\n")
        f.write("static const food_item_t food_items[FOOD_ITEM_COUNT] = {\n")
        for name, _, _, _ in items:
            f.write(f"    {{ \"{name}\", &food_{name}_img }},\n")
        f.write("};\n")

    print(f"wrote {OUT} ({len(items)} items, {sum(len(d) for _,_,_,d in items)} bytes total)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
