#!/usr/bin/env python3
"""Pack scene PNGs into a single LVGL C header.

Scenes are *opaque* backgrounds (not glyphs) so they pack as RGB565
instead of ARGB8888 — halving the flash footprint per pixel. LVGL
natively renders RGB565 images via LV_COLOR_FORMAT_RGB565 with no
runtime conversion.

Each PNG lives in sprite_forge/scenes/<name>.png at native size
(typically 184×152, which the UI scales 2x to fill the 368×304 scene
area on the device — matches the pet's 2x pixel-art chunkiness).

Output: firmware/components/ui/include/ui_scenes.h

Author at the exact target dimensions in Piskel — no resize, no bbox
normalisation. Re-run after editing any sprite_forge/scenes/*.png.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ModuleNotFoundError:
    sys.exit("Pillow not installed — run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "sprite_forge" / "scenes"
OUT = (ROOT / "firmware" / "components" / "ui" / "include" / "ui_scenes.h")

# Stem -> emitted C name is `ui_scene_<stem>_img`. Add new scenes to
# this list (e.g. "bedroom", "kitchen") as the art lands; the UI's
# scene-swap logic picks among them via state.
SCENES = [
    "home",
]


def png_to_rgb565(path: Path) -> tuple[int, int, bytes]:
    """Open the PNG, flatten any alpha against opaque, and emit native-
    size RGB565 little-endian bytes (LVGL's expected order)."""
    img = Image.open(path).convert("RGB")    # alpha-flatten implicitly
    w, h = img.size
    rgb = img.tobytes()                      # 3 bytes per pixel (R, G, B)
    out = bytearray(w * h * 2)
    for i in range(w * h):
        r = rgb[i * 3 + 0]
        g = rgb[i * 3 + 1]
        b = rgb[i * 3 + 2]
        # RGB565: rrrrrggg gggbbbbb, little-endian on the panel.
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        out[i * 2 + 0] = rgb565 & 0xFF
        out[i * 2 + 1] = (rgb565 >> 8) & 0xFF
    return w, h, bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_data[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    with OUT.open("w") as f:
        f.write("// Generated by sprite_forge/scenes_to_c.py — do not edit by hand.\n")
        f.write("// Re-run after changing any sprite_forge/scenes/*.png.\n\n")
        f.write("#pragma once\n#include \"lvgl.h\"\n\n")
        for name in SCENES:
            src = SRC_DIR / f"{name}.png"
            if not src.exists():
                sys.exit(f"missing {src}")
            w, h, data = png_to_rgb565(src)
            c_name = f"ui_scene_{name}"
            f.write(emit_byte_array(c_name, data))
            f.write("\n\n")
            f.write(f"static const lv_image_dsc_t {c_name}_img = {{\n")
            f.write("    .header = {\n")
            f.write("        .magic  = LV_IMAGE_HEADER_MAGIC,\n")
            f.write("        .cf     = LV_COLOR_FORMAT_RGB565,\n")
            f.write(f"        .w      = {w},\n")
            f.write(f"        .h      = {h},\n")
            f.write(f"        .stride = {w * 2},\n")
            f.write("    },\n")
            f.write(f"    .data      = {c_name}_data,\n")
            f.write(f"    .data_size = sizeof({c_name}_data),\n")
            f.write("};\n\n")
            total += len(data)
    print(f"wrote {OUT} ({len(SCENES)} scenes, {total} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
