#!/usr/bin/env python3
"""Convert sprite_forge/ui/*.png chrome PNGs into an LVGL C header.

Currently packs the care-dock button states. As more chrome is drawn
(food-picker tile, gear, back arrow, modal frame), add their stems to
BUTTONS below. Each PNG is embedded as-is at native size — no resize,
no bbox normalisation. Author at the exact target dimensions in Piskel.

Output: firmware/components/ui/include/ui_buttons.h
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ModuleNotFoundError:
    sys.exit("Pillow not installed — run: pip install -r requirements.txt")

ROOT = Path(__file__).resolve().parent.parent
UI_DIR = ROOT / "sprite_forge" / "ui"
OUT = ROOT / "firmware" / "components" / "ui" / "include" / "ui_buttons.h"

# Stem -> emitted C name is `<stem>_img`. PNG must live at UI_DIR/<stem>.png.
BUTTONS = [
    "btn_dock_raised",
    "btn_close_raised",
    "icon_chart",
    "icon_close",
    # icon_cog / icon_menu / btn_menu_raised removed — replaced by a bare
    # bar-chart icon with an extended click area; matches the stat-icon
    # style and reads as "open stats panel" directly.
]


def png_to_argb8888(path: Path) -> tuple[int, int, bytes]:
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    rgba = img.tobytes()
    out = bytearray(w * h * 4)
    for i in range(w * h):
        out[i * 4 + 0] = rgba[i * 4 + 2]
        out[i * 4 + 1] = rgba[i * 4 + 1]
        out[i * 4 + 2] = rgba[i * 4 + 0]
        out[i * 4 + 3] = rgba[i * 4 + 3]
    return w, h, bytes(out)


def emit_byte_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}_data[] = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("// Generated by sprite_forge/ui_buttons_to_c.py — do not edit by hand.\n")
        f.write("// Re-run after changing any sprite_forge/ui/*.png.\n\n")
        f.write("#pragma once\n#include \"lvgl.h\"\n\n")
        for name in BUTTONS:
            src = UI_DIR / f"{name}.png"
            if not src.exists():
                sys.exit(f"missing {src}")
            w, h, data = png_to_argb8888(src)
            f.write(emit_byte_array(name, data))
            f.write("\n\n")
            f.write(f"static const lv_image_dsc_t {name}_img = {{\n")
            f.write("    .header = {\n")
            f.write("        .magic  = LV_IMAGE_HEADER_MAGIC,\n")
            f.write("        .cf     = LV_COLOR_FORMAT_ARGB8888,\n")
            f.write(f"        .w      = {w},\n")
            f.write(f"        .h      = {h},\n")
            f.write(f"        .stride = {w * 4},\n")
            f.write("    },\n")
            f.write(f"    .data      = {name}_data,\n")
            f.write(f"    .data_size = sizeof({name}_data),\n")
            f.write("};\n\n")
    print(f"wrote {OUT} ({len(BUTTONS)} buttons)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
