// ui implementation — build-order step 6: "now it's a pet". Stat bars at
// the top, pet placeholder in the middle, four care buttons at the bottom.
// Touch the buttons to restore the matching need; bars update immediately.

#include "ui.h"
#include "renderer.h"
#include "esp_log.h"
#include "lvgl.h"
#include "food_items.h"   // generated by sprite_forge/items_to_c.py

static const char *TAG = "ui";

// Pixel-art aesthetic (polish-gate D): sharp corners, thin solid borders.
// Defined up front so any of the modal/picker helpers below can reuse them.
#define UI_FRAME_COLOR    0x4a5566      // muted slate — borders + bar bg
#define UI_BG_COLOR       0x101820      // screen background
#define UI_FG_COLOR       0xe5e5e5      // text on dark
#define UI_BTN_BG         0x202830      // care-button face
#define UI_BTN_BG_PRESSED 0x303a45      // pressed feedback

// Stat bar handles — index matches need_t order below.
enum { NEED_HUNGER, NEED_HAPPINESS, NEED_ENERGY, NEED_HYGIENE, NEED_COUNT };
static lv_obj_t *s_bars[NEED_COUNT];

// Bar styling — distinct hues per need so all four stay readable at a glance.
static const uint32_t s_bar_colors[NEED_COUNT] = {
    0xff8a40,  // hunger — warm orange (food)
    0xffd166,  // happiness — yellow
    0x4a9aff,  // energy — blue
    0x66d9c2,  // hygiene — cyan
};
static const char *s_bar_labels[NEED_COUNT] = {
    "Hunger", "Happiness", "Energy", "Hygiene"
};

// Sleep view — overlay + animated "Zzz" floating above the pet for a few
// seconds after Rest is pressed. Pure UI state; pet_state still ticks
// normally underneath. Body sprite keeps its idle bob, which reads as a
// sleeping creature breathing.
#define SLEEP_VIEW_MS 6000

static lv_obj_t   *s_sleep_overlay;
static lv_obj_t   *s_sleep_zzz;
static lv_timer_t *s_sleep_end_timer;

static void sleep_view_clear(void)
{
    if (s_sleep_overlay) { lv_obj_del(s_sleep_overlay); s_sleep_overlay = NULL; }
    if (s_sleep_zzz)     { lv_obj_del(s_sleep_zzz);     s_sleep_zzz = NULL; }
    if (s_sleep_end_timer) {
        lv_timer_del(s_sleep_end_timer);
        s_sleep_end_timer = NULL;
    }
}

static void sleep_end_cb(lv_timer_t *t) { (void)t; sleep_view_clear(); }

static void sleep_view_enter(void)
{
    if (s_sleep_overlay) {           // already sleeping → restart the timer
        if (s_sleep_end_timer) {
            lv_timer_reset(s_sleep_end_timer);
        }
        return;
    }
    lv_obj_t *scr = lv_screen_active();

    // Translucent dim over the pet area only (keeps bars + buttons clear).
    s_sleep_overlay = lv_obj_create(scr);
    lv_obj_set_size(s_sleep_overlay, 368, 240);
    lv_obj_set_pos(s_sleep_overlay, 0, 100);
    lv_obj_set_style_bg_color(s_sleep_overlay, lv_color_hex(0x000020), 0);
    lv_obj_set_style_bg_opa(s_sleep_overlay, LV_OPA_60, 0);
    lv_obj_set_style_border_width(s_sleep_overlay, 0, 0);
    lv_obj_set_style_radius(s_sleep_overlay, 0, 0);
    lv_obj_remove_flag(s_sleep_overlay, LV_OBJ_FLAG_SCROLLABLE);

    // Floating "Z z z" label, animated upward + repeated.
    s_sleep_zzz = lv_label_create(scr);
    lv_label_set_text(s_sleep_zzz, "Z z z");
    lv_obj_set_style_text_color(s_sleep_zzz, lv_color_hex(0xa0c8ff), 0);
    lv_obj_set_style_text_font(s_sleep_zzz, &lv_font_unscii_16, 0);
    lv_obj_set_pos(s_sleep_zzz, 200, 150);

    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, s_sleep_zzz);
    lv_anim_set_values(&a, 150, 110);            // float up 40 px
    lv_anim_set_duration(&a, 1500);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_obj_set_y);
    lv_anim_start(&a);

    s_sleep_end_timer = lv_timer_create(sleep_end_cb, SLEEP_VIEW_MS, NULL);
    lv_timer_set_repeat_count(s_sleep_end_timer, 1);
}

// Food picker view (polish-gate C-Feed). Feed press opens a 5-item modal;
// picking an item drops the food sprite near the pet's mouth for ~1.5 s,
// then it vanishes and pet_state_feed() restores hunger. Until step 5's
// body has an `eat` animation strip, the pet keeps its idle bob while the
// food is on screen — reads as "looking at" the food, not unrealistic.
#define FOOD_EAT_MS 1500

static lv_obj_t   *s_food_modal;
static lv_obj_t   *s_food_dropped;
static lv_timer_t *s_food_eat_timer;

static void food_cleanup_dropped(void)
{
    if (s_food_dropped) { lv_obj_del(s_food_dropped); s_food_dropped = NULL; }
    if (s_food_eat_timer) {
        lv_timer_del(s_food_eat_timer);
        s_food_eat_timer = NULL;
    }
}

static void food_eat_complete_cb(lv_timer_t *t)
{
    (void)t;
    food_cleanup_dropped();
    pet_state_feed();
    ui_refresh_stats();
}

static void food_picked_cb(lv_event_t *e)
{
    int idx = (int)(intptr_t)lv_event_get_user_data(e);
    if (idx < 0 || idx >= FOOD_ITEM_COUNT) return;

    if (s_food_modal) { lv_obj_del(s_food_modal); s_food_modal = NULL; }
    food_cleanup_dropped();

    // Drop the picked food sprite just to the left of the pet's mouth.
    // Pet is at (120, 130), 64-pixel canvas scaled 2x => 128x128 footprint.
    // Source is 32x32; scale 2x to read at the same chunky pixel size.
    s_food_dropped = lv_image_create(lv_screen_active());
    lv_image_set_src(s_food_dropped, food_items[idx].img);
    lv_image_set_antialias(s_food_dropped, false);
    lv_image_set_scale(s_food_dropped, 256 * 2);   // 32 -> 64 px
    lv_obj_set_pos(s_food_dropped, 152, 200);

    s_food_eat_timer = lv_timer_create(food_eat_complete_cb, FOOD_EAT_MS, NULL);
    lv_timer_set_repeat_count(s_food_eat_timer, 1);
}

static void food_modal_dismiss_cb(lv_event_t *e)
{
    // Only fire on clicks on the backdrop itself, not bubbled from buttons.
    if (lv_event_get_target(e) != s_food_modal) return;
    if (s_food_modal) { lv_obj_del(s_food_modal); s_food_modal = NULL; }
}

static void food_picker_show(void)
{
    if (s_food_modal) return;
    lv_obj_t *scr = lv_screen_active();

    s_food_modal = lv_obj_create(scr);
    lv_obj_set_size(s_food_modal, 368, 448);
    lv_obj_set_pos(s_food_modal, 0, 0);
    lv_obj_set_style_bg_color(s_food_modal, lv_color_hex(0x000000), 0);
    lv_obj_set_style_bg_opa(s_food_modal, LV_OPA_70, 0);
    lv_obj_set_style_border_width(s_food_modal, 0, 0);
    lv_obj_set_style_radius(s_food_modal, 0, 0);
    lv_obj_set_style_pad_all(s_food_modal, 0, 0);
    lv_obj_remove_flag(s_food_modal, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(s_food_modal, food_modal_dismiss_cb,
                        LV_EVENT_CLICKED, NULL);

    // 5 items × 64 px + 4 × 8 gutter = 352; centered in 368 starting x=8.
    for (int i = 0; i < FOOD_ITEM_COUNT; i++) {
        lv_obj_t *btn = lv_button_create(s_food_modal);
        lv_obj_set_size(btn, 64, 64);
        lv_obj_set_pos(btn, 8 + i * 72, 180);
        lv_obj_set_style_radius(btn, 0, 0);
        lv_obj_set_style_bg_color(btn, lv_color_hex(UI_BTN_BG), 0);
        lv_obj_set_style_bg_color(btn, lv_color_hex(UI_BTN_BG_PRESSED),
                                  LV_STATE_PRESSED);
        lv_obj_set_style_border_width(btn, 2, 0);
        lv_obj_set_style_border_color(btn, lv_color_hex(UI_FRAME_COLOR), 0);
        lv_obj_set_style_pad_all(btn, 0, 0);
        lv_obj_set_style_shadow_width(btn, 0, 0);

        lv_obj_t *img = lv_image_create(btn);
        lv_image_set_src(img, food_items[i].img);
        lv_image_set_antialias(img, false);
        lv_image_set_scale(img, 256 * 2);          // 32 -> 64
        lv_obj_center(img);

        lv_obj_add_event_cb(btn, food_picked_cb, LV_EVENT_CLICKED,
                            (void *)(intptr_t)i);
    }
}

// Care action callbacks. Each restores its need (or opens the food picker
// for Feed) and immediately refreshes the bars. Rest also flips on the
// sleep overlay.
static void on_feed_cb(lv_event_t *e)  { (void)e; food_picker_show(); }
static void on_play_cb(lv_event_t *e)  { (void)e; pet_state_play();  ui_refresh_stats(); }
static void on_rest_cb(lv_event_t *e)  { (void)e; pet_state_rest();  sleep_view_enter(); ui_refresh_stats(); }
static void on_clean_cb(lv_event_t *e) { (void)e; pet_state_clean(); ui_refresh_stats(); }

static lv_obj_t *make_stat_bar(lv_obj_t *parent, const char *name,
                               int y, uint32_t color)
{
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, name);
    lv_obj_set_style_text_color(label, lv_color_hex(UI_FG_COLOR), 0);
    lv_obj_set_pos(label, 8, y);

    lv_obj_t *bar = lv_bar_create(parent);
    lv_bar_set_range(bar, 0, 100);
    lv_obj_set_size(bar, 220, 14);
    lv_obj_set_pos(bar, 120, y + 4);
    // Sharp rectangle main + indicator; 1 px slate border around the bar.
    lv_obj_set_style_radius(bar, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(bar, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(bar, lv_color_hex(0x303744), LV_PART_MAIN);
    lv_obj_set_style_bg_color(bar, lv_color_hex(color), LV_PART_INDICATOR);
    lv_obj_set_style_border_width(bar, 1, LV_PART_MAIN);
    lv_obj_set_style_border_color(bar, lv_color_hex(UI_FRAME_COLOR),
                                  LV_PART_MAIN);
    return bar;
}

static void make_care_button(lv_obj_t *parent, const char *text,
                             int x, int y, lv_event_cb_t cb)
{
    lv_obj_t *btn = lv_button_create(parent);
    lv_obj_set_size(btn, 80, 70);
    lv_obj_set_pos(btn, x, y);
    // Pixel-art button: sharp corners, 2 px slate border, dark face with
    // a slightly lighter pressed state for tactile feedback.
    lv_obj_set_style_radius(btn, 0, 0);
    lv_obj_set_style_bg_color(btn, lv_color_hex(UI_BTN_BG), 0);
    lv_obj_set_style_bg_color(btn, lv_color_hex(UI_BTN_BG_PRESSED),
                              LV_STATE_PRESSED);
    lv_obj_set_style_border_width(btn, 2, 0);
    lv_obj_set_style_border_color(btn, lv_color_hex(UI_FRAME_COLOR), 0);
    lv_obj_set_style_shadow_width(btn, 0, 0);
    lv_obj_t *lbl = lv_label_create(btn);
    lv_label_set_text(lbl, text);
    lv_obj_set_style_text_color(lbl, lv_color_hex(UI_FG_COLOR), 0);
    lv_obj_center(lbl);
    lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);
}

void ui_init(void)
{
    if (!renderer_lock(0)) {
        ESP_LOGE(TAG, "could not lock LVGL");
        return;
    }

    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, lv_color_hex(UI_BG_COLOR), 0);

    // Stat bars — 4 rows of (label + bar), top 92px of the screen.
    for (int i = 0; i < NEED_COUNT; i++) {
        s_bars[i] = make_stat_bar(scr, s_bar_labels[i],
                                  4 + i * 22, s_bar_colors[i]);
    }

    // Pet placeholder — slightly higher than step 3 to make room for the
    // bars; still horizontally centered on the 368-wide AMOLED.
    renderer_draw_pet(pet_state_get(), 120, 130);

    // Care buttons — bottom row, ~80x70 each, 8px gutter; total width
    // (4*80 + 3*8) = 344, centered in 368 by starting at x=12.
    make_care_button(scr, "Feed",  12,  368, on_feed_cb);
    make_care_button(scr, "Play",  100, 368, on_play_cb);
    make_care_button(scr, "Rest",  188, 368, on_rest_cb);
    make_care_button(scr, "Clean", 276, 368, on_clean_cb);

    renderer_unlock();
    ui_refresh_stats();
    ESP_LOGI(TAG, "stat bars + care buttons up (build-order:6)");
}

void ui_refresh_stats(void)
{
    const Pet *p = pet_state_get();
    if (p == NULL || s_bars[0] == NULL) return;
    if (!renderer_lock(0)) return;
    lv_bar_set_value(s_bars[NEED_HUNGER],    p->hunger,    LV_ANIM_OFF);
    lv_bar_set_value(s_bars[NEED_HAPPINESS], p->happiness, LV_ANIM_OFF);
    lv_bar_set_value(s_bars[NEED_ENERGY],    p->energy,    LV_ANIM_OFF);
    lv_bar_set_value(s_bars[NEED_HYGIENE],   p->hygiene,   LV_ANIM_OFF);
    renderer_unlock();
}

void ui_show_home(void)
{
    // TODO(build-order:6+): split current home screen into reusable screens
    //                       once menus / settings need to coexist.
}

void ui_show_emote(emote_id_t emote)
{
    (void)emote;
    // TODO(build-order:10): ~2 s speech bubble; synced via radio.
}
