"""Compile one trait catalogue for the firmware UI and pet voice service."""
import argparse
import json
from pathlib import Path
from pprint import pformat
ROOT=Path(__file__).resolve().parents[1]
traits=json.loads((ROOT/'data/pet_traits.json').read_text())
assert [t['key'] for t in traits]==['body_shape','body_color','eye_shape','eye_color','ear_shape','mouth_shape','pattern','personality']
assert len(traits[1]['values'])==6  # Six RGB palettes in pixel_pet.c.
assert [t['gene_count'] for t in traits]==[8,16,8,16,8,8,8,8]
assert all(t['mode'] in ('visible','personality','stored') for t in traits)
q=lambda s:json.dumps(s,ensure_ascii=True)
lines=['// Generated by scripts/generate_pet_traits.py. Do not edit.\n#pragma once\n',
       'static const pet_trait_t TRAITS[8] = {\n']
for t in traits:
 values=','.join(map(q,t['values']))
 desc=','.join(map(q,t.get('descriptions',[t['description']]*len(t['values']))))
 lines.append('    {'+f'{q(t["label"])}, {q(t["mode"])}, {len(t["values"])}, {{{values}}}, {{{desc}}}'+'},\n')
lines.append('};\n')
outputs={ROOT/'firmware/components/pet_state/include/pet_traits_data.h':''.join(lines),
 ROOT/'integrations/butler/pet_traits.py':'# Generated by scripts/generate_pet_traits.py. Do not edit.\nTRAITS = '+pformat(traits,width=100,sort_dicts=False)+'\n'}
check=argparse.ArgumentParser();check.add_argument('--check',action='store_true');args=check.parse_args()
for p,text in outputs.items():
 if args.check:assert p.read_text()==text,f'Stale generated catalogue: {p}'
 else:p.write_text(text)
print('Trait catalogues match' if args.check else 'Generated firmware and voice trait catalogues')
