"""One five-character catalogue for device UI and versioned pet voice context."""
import argparse,json
from pathlib import Path
from pprint import pformat
ROOT=Path(__file__).resolve().parents[1];chars=json.loads((ROOT/'data/pet_characters.json').read_text())
assert [c['key'] for c in chars]==['sprout','bunny','penguin','kitten','dragon']
q=lambda s:json.dumps(s,ensure_ascii=True)
s='// Generated by scripts/generate_pet_characters.py.\n#pragma once\nstatic const pet_character_t CHARACTERS[PET_CHARACTER_COUNT] = {\n'
for c in chars:s+='{'+q(c['name'])+','+q(c['description'])+'},\n'
s+='};\n'
outputs={ROOT/'firmware/components/pet_state/include/pet_characters_data.h':s,ROOT/'integrations/butler/pet_characters.py':'# Generated by scripts/generate_pet_characters.py\nCHARACTERS = '+pformat(chars,sort_dicts=False,width=100)+'\n'}
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args()
for path,text in outputs.items():
 if args.check:assert path.read_text()==text,f'Stale catalogue: {path}'
 else:path.write_text(text)
print('Character catalogues match' if args.check else 'Generated character catalogues')
