#!/usr/bin/env python3
"""Compile the supplied MIDI library to flash-resident note spans. Requires mido 1.3.3.
Tempo changes, overlapping notes, sustain, velocity and channel gain are retained.
The device uses toy instruments, mono output, and no MIDI effects/pitch modulation.
"""
import json
from collections import defaultdict, deque
from pathlib import Path
import mido

ROOT = Path(__file__).resolve().parents[1]
FILES = [
    ('baabaablacksheep', 'Baa Baa Black Sheep'),
    ('happy_and_you_know', "If You're Happy"),
    ('humpty_dumpty', 'Humpty Dumpty'),
    ('jack_and_jill', 'Jack and Jill'),
    ('jolly_good_fellow', 'Jolly Good Fellow'),
    ('london_bridge', 'London Bridge'),
    ('mary_had_lamb', 'Mary Had a Little Lamb'),
    ('old_mac_donald', 'Old MacDonald'),
    ('twinkle_little_star', 'Twinkle Twinkle'),
]

def compile_song(path):
    midi = mido.MidiFile(path)
    if midi.type == 2:
        raise ValueError('Asynchronous MIDI tracks are unsupported')
    active = defaultdict(deque)
    held = [[] for _ in range(16)]
    pedal = [False]*16
    program = [0]*16
    volume = [100]*16
    expression = [127]*16
    notes = []
    now = 0.0

    def finish(note):
        start, pitch, velocity, instrument = note
        notes.append([round(start*1000), max(1, round((now-start)*1000)), pitch, velocity, instrument])

    def release_held(channel):
        for note in held[channel]:
            finish(note)
        held[channel].clear()

    for msg in midi:  # Mido merges synchronous tracks and applies each tempo change.
        now += msg.time
        if msg.is_meta:
            continue
        ch = getattr(msg, 'channel', 0)
        if msg.type == 'program_change':
            program[ch] = msg.program
        elif msg.type == 'control_change':
            if msg.control == 7:
                volume[ch] = msg.value
            elif msg.control == 11:
                expression[ch] = msg.value
            elif msg.control == 64:
                pedal[ch] = msg.value >= 64
                if not pedal[ch]:
                    release_held(ch)
            elif msg.control == 121:
                pedal[ch] = False
                expression[ch] = 127
                release_held(ch)
            elif msg.control in (120, 123):
                for key in list(active):
                    if key[0] == ch:
                        while active[key]:
                            note = active[key].popleft()
                            if pedal[ch] and msg.control == 123:
                                held[ch].append(note)
                            else:
                                finish(note)
                if msg.control == 120:
                    release_held(ch)
        elif msg.type == 'note_on' and msg.velocity:
            velocity = round(msg.velocity*volume[ch]*expression[ch]/(127*127))
            # A dedicated percussion timbre is outside the GM program range.
            active[ch, msg.note].append((now, msg.note, velocity, 128 if ch == 9 else program[ch]))
        elif msg.type == 'note_off' or (msg.type == 'note_on' and not msg.velocity):
            if active[ch, msg.note]:
                note = active[ch, msg.note].popleft()
                if pedal[ch] and ch != 9:
                    held[ch].append(note)
                else:
                    finish(note)
    for queue in active.values():
        for note in queue:
            finish(note)
    for ch in range(16):
        release_held(ch)
    notes = sorted(n for n in notes if n[3])
    if not notes:
        raise ValueError('Empty song')
    # Trim encoder count-in/trailing silence, keeping rests inside the song.
    offset = notes[0][0]
    for note in notes:
        note[0] -= offset
    edges = sorted((t, d) for n in notes for t,d in ((n[0],1),(n[0]+n[1],-1)))
    count = maximum = 0
    for _, delta in edges:
        count += delta
        maximum = max(maximum, count)
    if maximum > 64:
        raise ValueError(f'{path.name}: {maximum} voices exceeds the 64-voice budget')
    return notes, max(n[0]+n[1] for n in notes), maximum


def main():
    out = ['// Generated by scripts/import_midi.py; edit the MIDI sources, not this file.']
    catalog = []
    for index, (filename, title) in enumerate(FILES):
        notes, duration, voices = compile_song(ROOT/'assets/music'/f'{filename}.mid')
        out.append(f'static const music_note_t music_notes_{index}[] = {{')
        out.extend('    {' + ','.join(map(str, n)) + '},' for n in notes)
        out.append('};')
        catalog.append(f'    {{{json.dumps(title)}, music_notes_{index}, {len(notes)}, {duration}}},')
        print(f'{title}: {len(notes)} notes, {duration/1000:.1f}s, {voices} simultaneous voices')
    out += ['static const music_song_t music_songs[] = {', *catalog, '};', '']
    (ROOT/'firmware/components/audio/music_data.inc').write_text('\n'.join(out))

if __name__ == '__main__':
    main()
