"""Pack approved room art into 184x152 RGB565, displayed 2x without filtering."""
from pathlib import Path
from PIL import Image
root = Path(__file__).resolve().parents[1]
out = root / 'firmware/components/ui/include/pixel_rooms.h'
parts = ['// Generated by scripts/pack_pixel_rooms.py. Do not hand edit.\n#pragma once\n#include "lvgl.h"\n']
for kind in ('day', 'night'):
    im = Image.open(root / f'art/sprite-v3/room-{kind}-source.png').convert('RGB')
    im = im.resize((184, 152), Image.Resampling.NEAREST)
    im.save(root / f'art/sprite-v3/room-{kind}-device.png')
    data = bytearray()
    for r,g,b in im.getdata():
        n = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        data.extend((n & 255, n >> 8))
    parts.append(f'static const uint8_t room_{kind}_data[] = {{\n')
    parts.extend(','.join(f'0x{v:02x}' for v in data[i:i+24])+',\n' for i in range(0,len(data),24))
    parts.append('};\n')
    parts.append(f'static const lv_image_dsc_t room_{kind} = {{.header = {{.magic=LV_IMAGE_HEADER_MAGIC, .cf=LV_COLOR_FORMAT_RGB565, .w=184, .h=152, .stride=368}}, .data_size=sizeof(room_{kind}_data), .data=room_{kind}_data}};\n')
out.write_text(''.join(parts))
