"""Compile authored playtime atlases: keyed alpha, nearest-neighbour device pixels.
Source images are preserved. No drawing or generative transformations here.
"""
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'art/playtime-v1'
lines=['// Generated by scripts/pack_playtime_art.py\n#pragma once\n#include <stdint.h>\n']
for filename,columns,rows,size,name in [('stickers-source.png',4,3,24,'collectible'),('decorations-source.png',3,2,40,'decoration')]:
    source=Image.open(ART/filename).convert('RGBA')
    lines.append(f'static const uint32_t {name}_pixels[{columns*rows}][{size}*{size}] = {{\n')
    for i in range(columns*rows):
        x,y=i%columns,i//columns
        im=source.crop((round(x*source.width/columns),round(y*source.height/rows),round((x+1)*source.width/columns),round((y+1)*source.height/rows)))
        im.putdata([(0,0,0,0) if r>150 and b>140 and g<110 and min(r,b)>g*1.65 else (r,g,b,a) for r,g,b,a in im.getdata()])
        im=im.crop(im.getbbox());im.thumbnail((size-2,size-2),Image.Resampling.NEAREST)
        canvas=Image.new('RGBA',(size,size));canvas.paste(im,((size-im.width)//2,(size-im.height)//2));canvas.save(ART/f'{name}-{i}.png')
        data=[(a<<24)|(r<<16)|(g<<8)|b for r,g,b,a in canvas.getdata()]
        lines.append('{\n')
        for j in range(0,len(data),12):lines.append(','.join(f'0x{v:08x}' for v in data[j:j+12])+',\n')
        lines.append('},\n')
    lines.append('};\n')
(ROOT/'firmware/components/ui/include/playtime_art.h').write_text(''.join(lines))
print('Packed 12 stickers and 6 decorations: 66,048 bytes in flash')
