"""Pack generated complete sprites into fixed-size, alpha-keyed RGB565 C atlases.

This is asset compilation: split the authored atlas, remove its supplied chroma
key, fit device resolution with nearest-neighbour sampling, and encode pixels.
The source artwork is preserved verbatim in art/sprite-v3.
"""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / 'art/sprite-v3'
SIZE = 72
SHEETS = [
 ('poses-key.png', 2, ['wave','idle','happy','listen']),
 ('food-source.png', 3, ['apple','toast','cookie','apple_bite','toast_bite','cookie_bite']),
 ('care-source.png', 2, ['sleep','sleep_breathe','bath','bath_splash']),
 ('motion-source.png', 2, ['blink','talk','reach_left','reach_right']),
]
frames = []
for filename, columns, names in SHEETS:
    source = Image.open(ART / filename).convert('RGBA')
    rows = len(names) // columns
    for i, name in enumerate(names):
        x,y=i%columns,i//columns
        im=source.crop((round(x*source.width/columns),round(y*source.height/rows),
                        round((x+1)*source.width/columns),round((y+1)*source.height/rows)))
        # Broad magenta threshold also removes compressed/antialiased key edges.
        im.putdata([(0,0,0,0) if r>150 and b>140 and g<110 and min(r,b)>g*1.65
                    else (r,g,b,a) for r,g,b,a in im.getdata()])
        bounds=im.getbbox()
        if not bounds: raise ValueError(f'Empty sprite: {name}')
        im=im.crop(bounds)
        if filename=='food-source.png': size=(56,56)
        elif name.startswith('sleep'): size=(66,59)
        elif name.startswith('bath'): size=(66,62)
        else:
            factor=min(62/im.width,55/im.height)
            size=(round(im.width*factor),round(im.height*factor))
        im=im.resize(size,Image.Resampling.NEAREST)
        canvas=Image.new('RGBA',(SIZE,SIZE));canvas.paste(im,((SIZE-size[0])//2,69-size[1]))
        canvas.save(ART/f'{name}.png')
        data=[]
        for r,g,b,a in canvas.getdata():
            # zero reserved for transparency; plum outlines are nonzero.
            data.append(((r>>3)<<11)|((g>>2)<<5)|(b>>3) if a else 0)
        frames.append((name,data))
lines=['// Generated by scripts/pack_pet_sprites.py. Full illustrated sprite frames.\n#pragma once\n#include <stdint.h>\n']
lines.append('typedef enum { '+', '.join('SPRITE_'+n.upper() for n,_ in frames)+', SPRITE_COUNT } pet_sprite_id_t;\n')
lines.append(f'#define PET_SPRITE_SIZE {SIZE}\n')
lines.append('static const uint16_t pet_sprite_pixels[SPRITE_COUNT][PET_SPRITE_SIZE*PET_SPRITE_SIZE] = {\n')
for name,data in frames:
    lines.append(f'  /* {name} */ {{\n')
    for i in range(0,len(data),24):lines.append('    '+','.join(f'0x{x:04x}' for x in data[i:i+24])+',\n')
    lines.append('  },\n')
lines.append('};\n')
(ROOT/'firmware/components/ui/include/pet_sprites.h').write_text(''.join(lines))
print(f'Packed {len(frames)} frames, {len(frames)*SIZE*SIZE*2:,} bytes in flash')

# Authored 24px icons. Preserve the existing public icon numbering (flower at 5
# uses the new heart keepsake), and add toast/cookie at 7/8 for food selection.
source=Image.open(ART/'icons-source.png').convert('RGBA')
icons=[]
for i in range(8):
 x,y=i%4,i//4
 im=source.crop((round(x*source.width/4),round(y*source.height/2),round((x+1)*source.width/4),round((y+1)*source.height/2)))
 im.putdata([(0,0,0,0) if r>150 and b>140 and g<110 and min(r,b)>g*1.65 else (r,g,b,a) for r,g,b,a in im.getdata()])
 im=im.crop(im.getbbox());im.thumbnail((22,22),Image.Resampling.NEAREST)
 canvas=Image.new('RGBA',(24,24));canvas.paste(im,((24-im.width)//2,(24-im.height)//2))
 canvas.save(ART/f'icon-{i}.png');icons.append(canvas)
# Extract the largest separate soap bubble from the authored cluster for the
# five independently tappable bath targets (do not draw fake vector bubbles).
im=source.crop((round(3*source.width/4),0,source.width,round(source.height/2)))
im.putdata([(0,0,0,0) if r>150 and b>140 and g<110 and min(r,b)>g*1.65 else (r,g,b,a) for r,g,b,a in im.getdata()])
mask=im.getchannel('A');remaining={(x,y) for y in range(im.height) for x in range(im.width) if mask.getpixel((x,y))}
components=[]
while remaining:
 seed=remaining.pop();component=[seed];queue=[seed]
 while queue:
  x,y=queue.pop()
  for q in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
   if q in remaining:remaining.remove(q);queue.append(q);component.append(q)
 components.append(component)
component=max(components,key=len)
xs,ys=zip(*component);im=im.crop((min(xs),min(ys),max(xs)+1,max(ys)+1))
im.thumbnail((22,22),Image.Resampling.NEAREST)
canvas=Image.new('RGBA',(24,24));canvas.paste(im,((24-im.width)//2,(24-im.height)//2));icons.append(canvas)
canvas.save(ART/'icon-bubble.png')
lines=['// Generated by scripts/pack_pet_sprites.py\n#pragma once\n#include <stdint.h>\nstatic const uint32_t pet_icon_pixels[9][24*24] = {\n']
for im in icons:
 data=[(a<<24)|(r<<16)|(g<<8)|b for r,g,b,a in im.getdata()]
 lines.append('{\n')
 for i in range(0,len(data),12):lines.append(','.join(f'0x{x:08x}' for x in data[i:i+12])+',\n')
 lines.append('},\n')
lines.append('};\n');(ROOT/'firmware/components/ui/include/pet_icons.h').write_text(''.join(lines))
