"""Compile the authored treat atlas to device sprites/icons; no new drawing."""
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'art/special-foods-v1'
source=Image.open(ART/'treats-source.png').convert('RGBA')
# Authored gutters, inspected in the generated 1254px atlas. Equal thirds cut
# the first row's feet; these bounds preserve the complete authored poses.
rows=[0,455,870,1254]
assert source.size==(1254,1254)
names=['cupcake','pancakes','jelly','cake']
poses=[];icons=[]
for row in range(3):
 for col,name in enumerate(names):
  im=source.crop((round(col*source.width/4),rows[row],round((col+1)*source.width/4),rows[row+1]))
  im.putdata([(0,0,0,0) if r>150 and b>140 and g<110 and min(r,b)>g*1.65 else (r,g,b,a) for r,g,b,a in im.getdata()])
  bounds=im.getbbox();assert bounds
  im=im.crop(bounds)
  if row<2:
   # Same finished size/baseline as the existing three complete eating poses.
   im=im.resize((56,56),Image.Resampling.NEAREST)
   canvas=Image.new('RGBA',(72,72));canvas.paste(im,(8,13))
   data=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) if a else 0 for r,g,b,a in canvas.getdata()]
   poses.append(data)
  else:
   im.thumbnail((22,22),Image.Resampling.NEAREST)
   canvas=Image.new('RGBA',(24,24));canvas.paste(im,((24-im.width)//2,(24-im.height)//2))
   data=[(a<<24)|(r<<16)|(g<<8)|b for r,g,b,a in canvas.getdata()];icons.append(data)
  canvas.save(ART/(name+('-hold' if row==0 else '-bite' if row==1 else '-icon')+'.png'))
lines=['// Generated by scripts/pack_special_foods.py\n#pragma once\n#include <stdint.h>\n']
for name,data,ctype,size in [('special_food_pose',poses,'uint16_t',72),('special_food_icon',icons,'uint32_t',24)]:
 lines.append(f'static const {ctype} {name}[{len(data)}][{size}*{size}] = {{\n')
 for pixels in data:
  lines.append('{\n')
  for start in range(0,len(pixels),16):lines.append(','.join(hex(v) for v in pixels[start:start+16])+',\n')
  lines.append('},\n')
 lines.append('};\n')
(ROOT/'firmware/components/ui/include/special_food_art.h').write_text(''.join(lines))
print('Packed eight complete food poses and four icons')
