"""Compile authored genetic feature atlases. Cropping/keying only; originals retained."""
import argparse
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
ART=ROOT/'art/genetics-v1'
SPECS=[('ears',4,2,32,22,[(16,10),(30,12),(30,14),(28,22),(32,15),(26,15),(23,12),(32,14)]),
       ('eyes',4,2,26,10,[(23,7),(23,9),(25,7),(25,9),(25,6),(22,5),(25,10),(25,6)]),
       ('mouths',8,3,12,9,[(8,4),(10,4),(11,4),(5,5),(9,5),(11,5),(10,4),(7,6)]+[(9,8),(11,8),(11,8),(6,8),(10,8),(11,8),(10,7),(8,8)]+[(9,4),(11,4),(11,4),(6,5),(10,5),(11,5),(10,4),(8,5)]),
       ('markings',4,2,28,20,[(5,5),(28,20),(28,20),(23,18),(18,16),(15,13),(28,20),(28,20)])]
lines=['// Generated by scripts/pack_genetics.py; authored feature pixels, RGB565 key 0.\n#pragma once\n#include <stdint.h>\n']
for name,cols,rows,w,h,sizes in SPECS:
 src=Image.open(ART/(name+'-source.png')).convert('RGBA');frames=[]
 for i,size in enumerate(sizes):
  x,y=i%cols,i//cols
  im=src.crop((round(x*src.width/cols),round(y*src.height/rows),round((x+1)*src.width/cols),round((y+1)*src.height/rows)))
  im.putdata([(0,0,0,0) if a<180 or (r>150 and b>140 and g<110 and min(r,b)>g*1.65) else (r,g,b,255) for r,g,b,a in im.getdata()])
  # Remove isolated extraction noise, while retaining separate eyes/ear pairs.
  pts={(x,y) for y in range(im.height) for x in range(im.width) if im.getpixel((x,y))[3]}
  parts=[]
  while pts:
   q=[pts.pop()];part=[]
   while q:
    x,y=q.pop();part.append((x,y))
    for p in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
     if p in pts:pts.remove(p);q.append(p)
   parts.append(part)
  threshold=max(map(len,parts))//80
  for part in parts:
   if len(part)<threshold:
    for p in part:im.putpixel(p,(0,0,0,0))
  im=im.crop(im.getbbox()).resize(size,Image.Resampling.NEAREST)
  canvas=Image.new('RGBA',(w,h));canvas.paste(im,((w-size[0])//2,h-size[1]))
  frames.append([((r>>3)<<11)|((g>>2)<<5)|(b>>3) if a else 0 for r,g,b,a in canvas.getdata()])
 lines.append(f'static const uint16_t genetic_{name}[{len(frames)}][{w*h}] = {{\n')
 for frame in frames:lines.append('{'+','.join(hex(p) for p in frame)+'},\n')
 lines.append('};\n')
path=ROOT/'firmware/components/ui/include/genetic_art.h'
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
text=''.join(lines)
if args.check:assert path.read_text()==text,'Genetic art header is stale'
else:path.write_text(text)
print('Genetic artwork matches' if args.check else 'Packed 48 authored feature frames (29,568 bytes)')
