"""Compile food-only tint protection; artwork remains unchanged."""
import json
from pathlib import Path
from PIL import Image, ImageDraw
ROOT = Path(__file__).resolve().parents[1]
data = json.loads((ROOT / 'data/eating-food-masks.json').read_text())
lines = ['// Generated by scripts/pack_food_masks.py. [hold/bite][food][y][left,right-exclusive]\n',
         '#pragma once\n#include <stdint.h>\n',
         'static const uint8_t eating_food_spans[2][7][72][2] = {\n']
for pose in ('hold', 'bite'):
    lines.append('{\n')
    assert len(data[pose]) == len(data['foods']) == 7
    for name, polygon in zip(data['foods'], data[pose]):
        mask = Image.new('1', (72,72))
        ImageDraw.Draw(mask).polygon([tuple(p) for p in polygon], fill=1)
        spans=[]
        for y in range(72):
            xs=[x for x in range(72) if mask.getpixel((x,y))]
            spans.append('{%d,%d}' % (min(xs),max(xs)+1) if xs else '{0,0}')
        lines.append('/* '+name+' */ {'+','.join(spans)+'},\n')
    lines.append('},\n')
lines.append('};\n')
(ROOT/'firmware/components/ui/include/eating_food_masks.h').write_text(''.join(lines))
