"""Compile complete, independently illustrated characters; never compose body parts.

Uniform scale per animation group, fixed horizontal cell origin, whole-frame
baseline alignment. No individual feature transforms or per-frame stretch.
RGB565 run-length encoding preserves exact compiled pixels while saving flash.
"""
from pathlib import Path
from PIL import Image
import argparse,json,itertools
ROOT=Path(__file__).resolve().parents[1];ART=ROOT/'art/characters-v1'
NAMES=['idle','wave','happy','listen','blink','talk','reach_left','reach_right','sleep','sleep_breathe','bath','bath_splash']
FOODS=['apple','toast','cookie','cupcake','pancakes','jelly','cake']
FRAMES=NAMES+[f+'-'+p for p in ['hold','bite'] for f in FOODS]
characters=json.loads((ROOT/'data/pet_characters.json').read_text())
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
def keyed(im):
 im=im.convert('RGBA')
 im.putdata([(0,0,0,0) if a<128 or (r>150 and b>140 and g<110 and min(r,b)>g*1.65) else (r,g,b,255) for r,g,b,a in im.getdata()])
 return im

def cells(path,cols,rows,indices):
 im=Image.open(path)
 # Generated sheets can have uneven gutters. Explicit crop boundaries use only
 # empty background gaps, preserving entire illustrated frames and their scale.
 manifest=path.with_suffix('.json')
 grid=json.loads(manifest.read_text()) if manifest.exists() else {}
 xs=grid.get('columns',[round(i*im.width/cols) for i in range(cols+1)])
 ys=grid.get('rows',[round(i*im.height/rows) for i in range(rows+1)])
 assert len(xs)==cols+1 and len(ys)==rows+1
 assert xs[0]==ys[0]==0 and xs[-1]==im.width and ys[-1]==im.height
 assert all(a<b for a,b in zip(xs,xs[1:])) and all(a<b for a,b in zip(ys,ys[1:]))
 return [keyed(im.crop((xs[i%cols],ys[i//cols],xs[i%cols+1],ys[i//cols+1]))) for i in indices]

def register(group,maxw,maxh,centre=False):
 bounds=[im.getbbox() for im in group];assert all(bounds)
 scale=min(maxw/max(b[2]-b[0] for b in bounds),maxh/max(b[3]-b[1] for b in bounds))
 result=[]
 for im,b in zip(group,bounds):
  im=im.resize((round(im.width*scale),round(im.height*scale)),Image.Resampling.NEAREST)
  # Whole frame only: no contour/face edits, palettes, overlays or warping.
  baseline=im.getbbox()[3];canvas=Image.new('RGBA',(72,72))
  # Care props have their own centre; registration moves the complete image.
  box=im.getbbox();x=36-(box[0]+box[2])//2 if centre else (72-im.width)//2
  canvas.paste(im,(x,69-baseline))
  assert sum(a>0 for *_,a in canvas.getdata())==sum(a>0 for *_,a in im.getdata()),'Clipped artwork'
  result.append(canvas)
 return result

all_frames=[];words=[];offsets=[]
for character in characters:
 key=character['key'];folder=ART/key
 if key=='sprout':
  frames=[Image.open(ROOT/'art/sprite-v3'/(n+'.png')).convert('RGBA') for n in NAMES]
  for pose in ['hold','bite']:
   for f in FOODS:
    path=ROOT/'art/sprite-v3'/(f+('_bite' if pose=='bite' else '')+'.png') if f in FOODS[:3] else ROOT/'art/special-foods-v1'/(f+'-'+pose+'.png')
    frames.append(Image.open(path).convert('RGBA'))
 else:
  motion=cells(folder/'motion-source.png',4,3,range(12))
  care=folder/'care-source.png'
  frames=register(motion[:8],62,62 if key=='bunny' else 56)+register(cells(care,2,2,range(4)) if care.exists() else motion[8:],66,61,centre=care.exists())
  frames+=register(cells(folder/'food-source.png',4,4,list(range(7))+list(range(8,15))),56,56)
 assert len(frames)==26
 row=[]
 for name,im in zip(FRAMES,frames):
  if not args.check:
   folder.mkdir(parents=True,exist_ok=True);im.save(folder/(name+'.png'))
  pixels=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) if a else 0 for r,g,b,a in im.getdata()]
  row.append(len(words))
  for color,run in itertools.groupby(pixels):
   count=sum(1 for _ in run)
   while count:
    n=min(255,count);words.extend([n,color&255,color>>8]);count-=n
  # Verify lossless RLE round trip against all 5,184 compiled source pixels.
  decoded=[]
  for n in range(row[-1],len(words),3):decoded.extend([words[n+1]|words[n+2]<<8]*words[n])
  assert decoded==pixels
  all_frames.append(pixels)
 offsets.append(row)
lines=['// Generated by scripts/pack_characters.py. Complete sprites only.\n#pragma once\n#include <stdint.h>\n']
lines.append('typedef enum { '+', '.join('CHAR_'+n.upper().replace('-','_') for n in FRAMES)+', CHAR_FRAME_COUNT } character_frame_t;\n')
lines.append('static const uint32_t character_offsets['+str(len(characters))+'][CHAR_FRAME_COUNT] = {\n'+''.join('{'+','.join(map(str,row))+'},\n' for row in offsets)+'};\n')
lines.append('static const uint8_t character_rle[] = {\n')
for i in range(0,len(words),24):lines.append(','.join(hex(w) for w in words[i:i+24])+',\n')
lines.append('};\n')
text=''.join(lines);path=ROOT/'firmware/components/ui/include/character_sprites.h'
if args.check:assert path.read_text()==text,'Stale character atlas'
else:path.write_text(text)
print(f'{len(all_frames)} complete frames: {len(words):,} RLE bytes, {len(all_frames)*72*72*2:,} raw; all frames round-trip exactly')
